### PR TITLE
Restricted areas, vector functions, SID/restricted UI switches [needs test]

### PR DESCRIPTION
**Pull request by culebron**
#219 **UPDATE**: Here's the final version, test it please.

The branch is deployed here for tests:
http://culebron.github.io/atc/

For some reason, arriving aircrafts start climbing higher right after spawning. Can someone investigate? I've checked and can't see the reason.

### CODE REVIEW

**Comment by MaicomMR** [comment]
Man, u are a genious! Thanks for this :smiley:

**Comment by culebron** [comment]
@MaicomMR thanks! That's just geometry, I like it. :)

@zlsa @tedrek @glangford @nielsvdweide @harp71  please try this out on UUDD or your airports if you wish to add restricted areas.

**Comment by culebron** [comment]
I added both restricted area and SID display switches requested in #235.

**Comment by culebron** [comment]
Made some tests and adjustments. As I found out, bounding boxes did not cure the problem very well. Instead they often caused more calculation cycles when planes flew around a restricted area, touching the bbox boundary.

Also, there were serious CPU spikes when planes entered the area at shallow angle. I made it calculate the range not more often than every 1 km.

selection_046

Also, tried bbox calculation with 1km trick, but it did not help. In fact, using bbox caused higher CPU load. So, I fixed a problem that arised with bbox, and that's enough.

**Comment by glangford** [comment]
This is looking good @culebron , a couple of observations and suggestions:
- the rendering of the restricted areas is nice
- should there be a bigger penalty for going through a restricted area? Right now it is lower than missing the departure window.
- UUDD has a STAR route with fixes ITINA, RW. This passes directly through restricted area UUR-68, but arriving aircraft never received a penalty passing through there. (?)
- should any STAR go through the restricted area?
- this branch has the change to add buttons for enable/disable of SID display and restricted areas; should these changes be a separate pull request?
- when restricted areas are disabled, a bright red bar is displayed over the icon which is distracting. When SID display is disabled, nothing is displayed over the icon which I think is better.
- arriving aircraft are slow (200 knots)

**Comment by culebron** [comment]
> should there be a bigger penalty for going through a restricted area? Right now it is lower than missing the departure window.

Ok, will raise it a bit.

> UUDD has a STAR route with fixes ITINA, RW. This passes directly through restricted area UUR-68, but arriving aircraft never received a penalty passing through there. (?)

That's correct, because that area works from ground up to flight level 20 (200 feet). I'll try making the display similar to charts, so that the height range is clear.

> should any STAR go through the restricted area?

...and hence that STAR does not cross the area.

> this branch has the change to add buttons for enable/disable of SID display and restricted areas; should these changes be a separate pull request?

Ok, I can separate that branch.

> when restricted areas are disabled, a bright red bar is displayed over the icon which is distracting. When SID display is disabled, nothing is displayed over the icon which I think is better.

That was intended, since turning them off is less safe, hence incentivise to turn them on. If this is really so needed and so disturbing, we can remove this red indication. **What do others think?**

> arriving aircraft are slow (200 knots)

I checked with flightradar, you're right, they arrive at about 240kts, will increase the speed.

**Comment by culebron** [comment]
All items mentioned by @glangford  are fixed. Please write your opinions on the UI toggle. Should it be red when restricted areas are hidden, or not?

**Comment by culebron** [comment]
Test the branch here: http://culebron.github.io/atc/

**Pull request merged**
