### PR TITLE
Add support for SIDs

### LINKED ISSUE #228: Render standard instrument departure sequences on the canvas
I think most people will not be familiar with standard airport departure schemes, so a rendering on screen is needed. Here is an example of what it might look like for KSFO for example. I am using the departure colour with very little "ink" so it isn't a pain to look at.

ksfo sids
#224
#227

### PR DESCRIPTION
**Pull request by glangford**
#128
#147
#222

Fix #228

Adds an "SID" command that can be used rather than repetitively typing fix names for standard instrument departures.

ENGM example:
- SAS354 TAXI 19L C 8 S 250 SID NUVSA

The entry of the SID in this example replaces typing the sequence of fixes: GM442 GM603 VEMIN GM443 PEMUS NUVSA
- SIDS are defined in the airport definition files as simple arrays of fix names
- KSFO and ENGM have been updated; others can be updated later
- SIDS for these airports match the departure destinations that can be assigned
- completely optional to use

@zlsa please merge this last (in particular, after #222) - if there are merge conflicts, I will fix as needed. Thanks!

### CODE REVIEW

**Comment by glangford** [comment]
@nielsvdweide or @culebron I now have the charts for EHAM. Should we be adding STAR arrivals and SIDs to it?

For the current set of EHAM departure destinations (60, 85, 145, 180, 245, 330) do these correspond to particular SIDs or are they more or less random?

**Comment by nielsvdweide** [comment]
@Glangford

If you want to add sids and stars for Amsterdam EHAM, that would be awesome! Last time I updated Amsterdam I didn't put all the fixes in, neither did I look at departure or arrival plates.

I guess the departure headings are completely random, but I tried to put in different directions!

For the sids and stars, lot of them consist of fixes that are outside radar coverage. Maybe it's an option to expand the radar area?

**Comment by culebron** [comment]
@glangford That would be great. I'll pull this branch and try making SIDs for Galeão, will see if I encounter any bugs.

**Comment by glangford** [comment]
Perfeito.

**Comment by MaicomMR** [comment]
@glangford I can try make SIDs for Guarulhos(SBGR). I will learn more about, I'm long time out.

**Comment by nielsvdweide** [comment]
@glangford I can assist on making Amsterdam SIDS but i don't really know how to do that with the current code. Could you provide a basic layout which i can upgrade? 

Regards

**Comment by culebron** [comment]
Seems to work for me in KSFO. But when I tried adding SIDs for SBGL, I saw there are several problems: some departures suggest just doing 180deg turn after initial climb, and there's no fix to stick to. Also some SIDs work for several configurations, but require particular turns (turn right rather that left), and if we just send splanes by fixes, they might fly the wrong side of the airport, interfering with the traffic on final.

Here, taking off frow rw28, if plane is sent to YLA, it'll turn left, which is the shortest way, interfering with traffic on final to rw33:
selection_042

**Comment by glangford** [comment]
As a template, maybe the best guide would be to review ENGM as an example. See inline here (I wasn't able to make it an attachment)
- the departures section has "sids" inside with a name and an array of fixes
- the arrivals section has a STAR name just for documentation purposes, and a list of fixes defining the STAR

Let me know of any questions.

``` js
{
  "name": "Oslo Gardermoen International Airport (WIP)",
  "level": "hard",
  "radio": "Oslo",
  "icao": "ENGM",
  "magnetic_north": -2.8,
  "ctr_radius": 80,
  "position": ["N60d12m10.00", "E11d05m02.00"],
  "wind": {
    "angle": 190,
    "speed": 8
  },
  "fixes": {
    "ADOPI": ["N60d19m25.00", "E09d23m00.00"],
    "NIVDU": ["N60d16m20.00", "E09d51m50.00"],
    "VANUK": ["N60d53m20.00", "E10d28m25.00"],
    "BELGU": ["N61d12m45.00", "E10d35m50.00"],
    "GM456": ["N60d26m08.40", "E10d18m18.90"],
    "GM400": ["N60d16m51.69", "E10d16m42.90"],
    "GM402": ["N60d07m49.10", "E10d15m10.20"],
    "GM405": ["N60d01m37.40", "E10d10m42.60"],
    "GM407": ["N60d01m27.50", "E10d12m41.00"],
    "GM406": ["N59d55m02.10", "E10d10m49.70"],
    "GM408": ["N59d55m13.90", "E10d12m47.80"],
    "GM404": ["N59d48m52.00", "E10d15m25.00"],
    "GM409": ["N59d49m22.00", "E10d17m07.60"],
    "GM455": ["N59d44m55.80", "E10d21m32.10"],
    "GM410": ["N59d44m36.90", "E10d25m11.10"],
    "RIPAM": ["N59d19m40.00", "E09d45m00.00"],
    "ROXIM": ["N59d37m02.70", "E10d12m51.70"],
    "INGAR": ["N59d39m33.30", "E09d56m06.40"],
    "VALPU": ["N59d58m25.00", "E10d48m08.70"],

    "IDAMO": ["N59d59m00.90", "E12d10m16.70"],
    "GM401": ["N60d04m03.92", "E11d51m13.55"],
    "GM403": ["N59d55m29.50", "E11d44m41.90"],
    "GM411": ["N59d48m58.30", "E11d42m16.70"],
    "GM414": ["N59d49m18.70", "E11d40m29.10"],
    "GM413": ["N59d43m16.60", "E11d35m42.80"],
    "GM415": ["N59d43m57.30", "E11d34m09.00"],
    "GM412": ["N59d39m04.50", "E11d25m38.30"],
    "GM417": ["N59d39m55.70", "E11d24m37.90"],
    "GM454": ["N59d37m09.60", "E11d16m30.10"],
    "GM416": ["N59d37m49.70", "E11d13m01.20"],
    "DEVKU": ["N59d27m07.90", "E11d15m34.40"],
    "LUNIP": ["N59d11m00.00", "E11d18m55.00"],
    "DIDAX": ["N59d25m10.90", "E11d27m51.40"],
    "INSUV": ["N59d55m32.24", "E11d06m50.58"],

    "EXUDA": ["N60d23m50.80", "E09d55m34.80"],
    "GM451": ["N60d08m50.37", "E10d12m44.83"],
    "UTEXO": ["N59d56m16.10", "E10d05m30.20"],
    "GM427": ["N60d19m39.90", "E10d19m03.00"],
    "GM428": ["N60d27m56.10", "E10d26m32.60"],
    "GM429": ["N60d34m22.60", "E10d28m47.00"],
    "GM435": ["N60d34m01.90", "E10d30m37.60"],
    "GM430": ["N60d40m06.60", "E10d35m26.40"],
    "GM434": ["N60d39m28.20", "E10d36m59.70"],
    "GM431": ["N60d44m22.30", "E10d45m37.90"],
    "GM433": ["N60d43m29.50", "E10d46m41.30"],
    "GM452": ["N60d46m17.90", "E10d55m06.60"],
    "GM432": ["N60d45m41.10", "E10d58m39.60"],
    "BAVAD": ["N60d27m58.00", "E11d05m04.00"],
    "AGNIL": ["N60d56m05.10", "E10d49m52.20"],

    "INREX": ["N61d00m50.00", "E12d13m00.00"],
    "IXUMA": ["N60d49m08.50", "E11d59m23.00"],
    "GM418": ["N60d39m04.30", "E11d47m43.80"],
    "GM453": ["N60d38m39.70", "E11d51m30.50"],
    "GM419": ["N60d34m12.60", "E11d55m50.00"],
    "GM425": ["N60d34m40.80", "E11d57m34.20"],
    "GM420": ["N60d28m18.70", "E12d00m05.70"],
    "GM424": ["N60d28m28.50", "E12d02m06.90"],
    "GM421": ["N60d22m05.60", "E12d00m00.30"],
    "GM423": ["N60d21m54.90", "E12d02m01.50"],
    "GM422": ["N60d15m45.40", "E11d57m17.40"],
    "TITLA": ["N60d25m16.90", "E11d24m09.80"],
    "KEGET": ["N60d05m23.00", "E12d15m17.60"],
    "ESEBA": ["N60d00m45.76", "E12d23m32.45"],
    "GM426": ["N60d06m39.90", "E11d54m32.90"],
    "GM447": ["N59d55m57.36", "E11d47m31.83"],

    "ODUDI": ["N60d24m22.30", "E11d12m06.80"],
    "OSPAD": ["N60d24m03.57", "E11d14m19.43"],
    "XINLO": ["N60d21m18.92", "E11d10m20.60"],
    "XIVTA": ["N60d20m24.30", "E11d12m11.28"],

    "GM602": ["N60d03m30.00", "E11d04m00.00"],
    "GM604": ["N60d08m00.00", "E11d05m00.00"],
    "GM444": ["N60d03m33.00", "E11d14m25.00"],
    "GM442": ["N60d08m28.90", "E10d57m11.30"],
    "GM603": ["N60d09m20.00", "E10d48m00.00"],

    "KUBUB": ["N59d32m30.72", "E10d41m50.00"],
    "TOR":   ["N59d10m08.80", "E10d15m33.36"],
    "ODAXI": ["N59d54m31.00", "E10d33m10.76"],
    "VIBUK": ["N60d10m00.00", "E11d26m55.00"],
    "MASEV": ["N60d10m40.00", "E12d32m05.00"],
    "VEMIN": ["N60d13m50.00", "E10d47m05.00"],
    "NANON": ["N59d35m19.11", "E10d23m59.46"],
    "GM443": ["N60d26m46.00", "E11d13m30.00"],
    "PEMUS": ["N60d45m00.00", "E11d26m30.00"],
    "NUVSA": ["N61d04m30.03", "E11d28m55.12"]
  },
  "runways":[
    {
      "name":        ["19R", "01L"],
      "name_offset": [[0, 0], [0, 0]],
      "end":    [ ["N60d12m57.84", "E11d05m29.99"], ["N60d11m06.00", "E11d04m25.48"]],
      "length":      3.60,
      "ils":         [true, true]
    },
    {
      "name":        ["19L", "01R"],
      "name_offset": [[0, 0], [0, 0]],
      "end":    [["N60d12m04.35", "E11d07m20.95"], ["N60d10m32.72", "E11d06m28.02"]],
      "length":      2.95,
      "ils":         [true, true]
    }
  ],
  "departures": {
    "airlines": [
      ["sas", 11],
      ["afl", 5],
      ["nax", 5],
      ["fdx", 1],
      ["ups", 1]
    ],
    "sids": {
      "MASEV": ["GM604", "GM444", "VIBUK", "MASEV"],
      "TOR": ["GM604", "GM602", "KUBUB", "TOR"],
      "NUVSA": ["GM442", "GM603", "VEMIN", "GM443", "PEMUS", "NUVSA"]
    },
    "destinations": [
      20, 95, 200
    ],
    "type": "random",
    "offset": 0,
    "frequency": 28
  },
  "arrivals": [
    {
      "_name":  "ADOPI 3M",
      "radial":   290,
      "speed":    250,
      "fixes":    ["ADOPI", "EXUDA", "GM428", "GM429", "GM430", "GM431", "GM452", "BAVAD"],
      "airlines":  [
        ["nax", 2],
        ["sas", 5]
      ],
      "type": "random",
      "offset": 2,
      "frequency": 4,
      "altitude":  10000
    },
    {
      "_name":  "BELGU 3M",
      "radial":   350,
      "speed":    250,
      "fixes":   ["BELGU", "AGNIL", "GM432", "GM433", "GM434", "GM435", "BAVAD"],
      "airlines":  [
        ["nax", 1],
        ["sas", 1],
        ["fdx", 1]
      ],
      "type": "wave",
      "offset": 0,
      "frequency": 8,
      "altitude":  10000
    },
    {
      "_name":  "ESEBA 4M",
      "radial":   110,
      "speed":    250,
      "fixes":    ["ESEBA", "KEGET", "GM422", "GM423", "GM423", "GM424", "GM425", "GM453", "TITLA"],
      "airlines":  [
        ["sas", 1],
        ["afl", 1]
      ],
      "type": "random",
      "offset": 3,
      "frequency": 4,
      "altitude":  10000
    },
    {
      "_name":  "INREX 4M",
      "radial":   30,
      "speed":    250,
      "fixes":    ["INREX", "IXUMA", "GM418", "GM419", "GM420", "GM421", "TITLA"],
      "airlines":  [
        ["sas", 1],
        ["afl", 1]
      ],
      "type": "cyclic",
      "offset": 0,
      "frequency": 8,
      "altitude":  10000
    },
    {
      "_name":  "LUNIP 4M",
      "radial":   170,
      "speed":    250,
      "fixes":    ["LUNIP", "DIDAX", "GM447", "GM426", "GM422", "GM423", "GM424", "GM425", "GM453", "TITLA"],
      "airlines":  [
        ["nax", 1],
        ["sas", 1]
      ],
      "type": "random",
      "frequency": 4,
      "altitude":  10000
    },
    {
      "_name":  "RIPAM 4M",
      "radial":   225,
      "speed":    250,
      "fixes":    ["RIPAM", "INGAR", "UTEXO", "GM451", "GM427", "GM428", "GM429", "GM430", "GM431", "GM452", "BAVAD"],
      "airlines":  [
        ["sas", 1],
        ["nax", 1]
      ],
      "type": "random",
      "offset": 0,
      "frequency": 4,
      "altitude":  10000
    }

  ]
}
```

**Comment by glangford** [comment]
> Seems to work for me in KSFO. But when I tried adding SIDs for SBGL, I saw there are several problems: some departures suggest just doing 180deg turn after initial climb, and there's no fix to stick to. Also some SIDs work for several configurations, but require particular turns (turn right rather that left), and if we just send splanes by fixes, they might fly the wrong side of the airport, interfering with the traffic on final.

Yes, KLAX has an issue or two as well with some SIDs that have radar vectors in the middle of them. 

For SBGL, can we just pick a subset of SIDs that work? (Edit: Another possibility is to insert "virtual" fixes, to get the right behaviour).

**Comment by harp71** [comment]
SIDs also have suffixes like 2E or 1N, e.g. MASEV should be named MASEV 1E.

2015-11-09 15:23 GMT+01:00 Glenn Langford notifications@github.com:

**Comment by glangford** [comment]
> SIDs also have suffixes like 2E or 1N, e.g. MASEV should be named MASEV 1E.

This was intentional on my part to leave off suffixes and version numbers for simplicity (and less typing). If they need to be added in specific instances, let's raise an issue and it can be fixed.

**Comment by glangford** [comment]
@zlsa This is now ready for merge.

**Comment by nielsvdweide** [comment]
@Glangford and others, I will take care of adding Sids and Stars for amsterdam! I will make a pull request for that somewhere this week.

**Comment by MaicomMR** [comment]
@culebron Take a look at these letters, these are the official website of Brazilian aviation.

http://www.aisweb.aer.mil.br/download/?arquivo=7cc987b4-370f-1032-95e7-72567f175e3a
http://www.aisweb.aer.mil.br/download/?arquivo=1851023c-8ffa-1032-8701-72567f175e3a
http://www.aisweb.aer.mil.br/download/?arquivo=6c0d0ffc-21a9-1032-95e7-72567f175e3a

Here is the official website:
http://www.aisweb.aer.mil.br/?i=cartas&filtro=1&nova=1

**Comment by zlsa** [comment]
@glangford: merged.

**Pull request closed without merging**
