### PR TITLE
Even more waypoints for LOWW 11

### PR DESCRIPTION
**Pull request by Alpi-no**
Need those for stars

### CODE REVIEW

**Comment by erikquinn** [comment]
hey @jakobeng1303, would you mind if we held off on these until we can actually implement the STARs? It makes more sense to merge all of those things at once, rather than in multiple pieces, as it helps keep a cleaner and more clear commit history.

**Comment by Alpi-no** [comment]
@erikquinn that makes complete sense as they are only needed for stars anyway. I'm planning to add some for runway 16 as well, but I probably won't have time til about Friday or Saturday

**Comment by erikquinn** [comment]
@jakobeng1303 Okay, sounds good. I'll close this PR for now, and you can reopen another with the STARs added once the capability is added over the next week or so. :smile:

**Comment by Alpi-no** [comment]
@erikquinn stars and fixes for runway 11&16 at LOWW are finished. Hopefully they work! I'm not entirely sure, whether I fully understand the mechanism behind it, but I hope I didn't delete anything important or any brackets :D

**Comment by erikquinn** [comment]
@jakobeng1303 Okay, great! :+1: Hang on to them, and once the STAR logic is added, we can see if they are working properly!

**Pull request closed without merging**
