### PR TITLE
EHAM-fix

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by eliuuk** [comment]
Thanks for fixing that - haven't had the time recently to resolve these sorts of things. Just wondering if the arrival 'REDFA1A' is still pronouncing correctly? There was an instance where all Air India callsigns were being pronounced letter-by-letter (A-I-R-I-N-D-I-A) instead of as if it was one word because it was capitalised.

REDFA can be pronounced without being said letter-by-letter so just wanted to check that so it saves time - the woman is already slow enough to cope with the transmissions!

**Comment by erikquinn** [comment]
>Thanks for fixing that - haven't had the time recently to resolve these sorts of things. Just wondering if the arrival 'REDFA1A' is still pronouncing correctly? There was an instance where all Air India callsigns were being pronounced letter-by-letter (A-I-R-I-N-D-I-A) instead of as if it was one word because it was capitalised.

Sounds like a new bug!

>REDFA can be pronounced without being said letter-by-letter so just wanted to check that so it saves time - the woman is already slow enough to cope with the transmissions!

We can definitely speed her up, but she starts to sound crazy. :wink:

**Comment by erikquinn** [comment]
@themikeylaw We are in the process of getting everything moved over to the new home of the simulator: [https://github.com/openscope/openscope](https://github.com/openscope/openscope). Would you be able to close and reopen this pull request at the new repository? All issues and pulls here will soon be closed, and I want to make sure this one ends up getting merged into the sim. 😄

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), and thus, all pull requests are being closed. If you would still like to see this merged into the simulator, please reopen the pull request at the new repo. Thank you!

Closing this PR.

**Pull request closed without merging**
