### PR TITLE
Munich Airport v2 and time-warp 5

### PR DESCRIPTION
**Pull request by harp71**
New with lon/lat, STARs, many airlines, quite balanced, fun to play. Different color for time-warp 2 and 5.

### CODE REVIEW

**Comment by glangford** [comment]
:+1:

**Comment by harp71** [comment]
thx, i hope i got the git-logic right this time

2015-11-03 14:15 GMT+01:00 Glenn Langford notifications@github.com:

**Comment by glangford** [comment]
@harp71 Munich looks great! A small suggestion for your next pull request:
- there are many advantages to making changes in a separate topic branch, see a discussion here for example:
  https://git-scm.com/book/de/v1/Git-Branching-Branching-Workflows

**Comment by harp71** [comment]
yeah, thats what i intended to to. i get it next time, hopefully :)

2015-11-03 14:24 GMT+01:00 Glenn Langford notifications@github.com:

**Comment by harp71** [comment]
Is there a problem with merging this?

**Comment by glangford** [comment]
@harp71 you have to wait for @zlsa, he is the only one with permission to merge.

**Comment by zlsa** [comment]
Really sorry about the delay, I've been really busy recently.

**Comment by glangford** [comment]
@zlsa No worries, thanks for the merge!

**Comment by harp71** [comment]
thx!

2015-11-09 15:32 GMT+01:00 Jon Ross notifications@github.com:

**Comment by harp71** [comment]
"I´m usefull, i´m having a wonderfull time!" (Dr. Zoidberg)

2015-11-09 15:35 GMT+01:00 harP emailanharp@gmail.com:

**Pull request merged**
