### PR TITLE
Added KSNA

### PR DESCRIPTION
**Pull request by BSthePilot**
ksna.json updated as suggested, airport.js also updated.

### CODE REVIEW

**Comment by Diastro** [comment]
Something isn't right. I cloned your repo and the sim isn't able to load your airport (I don't have the time to investigate right now...).

Also, I think your branch is out of date from upstream.
Take a look at this : https://help.github.com/articles/syncing-a-fork/

**Comment by zlsa** [comment]
Hi @BSthePilot, there are multiple issues with this PR.
1. The JSON file is missing many commas; for example, after ICAO, and between the two runway blocks.
2. You should update your branch to the state of the master branch (zlsa/atc); otherwise, git has to merge all commits made since your fork.

Otherwise, the airport file looks okay, but I haven't yet been able to get it to work properly.

**Comment by BSthePilot** [comment]
Hey, sorry for the delay. I am not entirely sure how to make those changes since I'm not familiar with the formatting required, so I'll have to put it on the backburner for now. Sorry!

**Comment by ufkes** [comment]
@BSthePilot a json validator like http://jsonlint.com/ will help you with the formatting. You're just missing a colon at ICAO and a bunch of commas all over the file.

**Pull request closed without merging**
