### PR TITLE
KJFK Update

### PR DESCRIPTION
**Pull request by jpeterson1346**
Updated configuration to favor 31L/R. Reworked STARS and their traffic.
SIDS now have climbouts incorporated in them (e.g., Canarsie, Breezy
Point). This better handles departing traffic by directing aircraft in
the correct direction depending on the departure gate.

### CODE REVIEW

**Comment by jpeterson1346** [comment]
The New York airspace (N90 TRACON) is very congested. Traffic throughout the region is heavily restricted to coordinated procedures so that the three major and countless minor airfields can operate efficiently. On top of that, KJFK Airport is New York's main international gateway (though that can be argued by Newarkers). Nonetheless, heavy traffic arriving and departing is essentially constant with surges during the morning rush, afternoon international arrivals rush, and the evening departure rush. I'm going to include some (what I find useful) guides to managing traffic in the region, though keep in mind, you are free to deviate from these methods at your convenience.

## Overview

screenshot 22

The way the configuration is setup in the game _favors_ departures and arrivals on the 31s (**31L**/**31R**). The SIDS in the kjfk.json file reflect the preferred configuration and have corresponding climbouts. Further, arriving traffic--particularly ROBER# and PARCH# arrivals--is vectored and descended to altitudes and speeds that favor **31L**/**31R** arrivals.

## Departures

There are three SIDS from KJFK: JFK# (Kennedy; "Ken-e-dee" #), SKORR# ("score" #), and DEEZZ# ("deez" #). In the real world, these departures are assigned based on
1. assigned runway,
2. departure gate (which I will briefly explain in a minute),
3. airport configuration,
4. aircraft equipment, and,
5. local time.

Unfortunately in this simulation, neither us editors nor controllers have that kind of flexibility. Thus, the setup is as follows.

### Climbout

##### JFK# Climbs

In the simulation, JFK# is only valid for departures on **31L** and on **31R**. _In the real world, JFK# is the standard SID for all departures (regardless of runway) at KJFK, except for RNAV-equipped aircraft (a certain type of equipment that enables greater ability to navigate via inferred distances and bearings to radio beacons) departing **31L** or **31R**, where SKORR# is assigned. Furthermore, the JFK# departure defines certain "climbs" for **31L/R** and **22R** departures, depending on an aircraft's route of flight, though the specifics are not necessarily applicable to the current state of the simulation. In short, departures to the southeast (SOUTH 1 gates:_ ARD_,_ RNGRR_,_ RBV_,_ DIXIE_,_ WHITE_) are assigned the Breezy Point climb whereas all other gates (i.e., other directions) are assigned the Canarsie climb  (for turbojets)._ For the purpose of the simulation, a similar approach was given.

image

Since departures from both runways require a climbing left turn direct CRI (Canarsie) VOR/DME within JFK 4.5 DME (i.e., hard left turn as soon as able after takeoff), parallel departures in short succession will cause a loss of separation. Likewise, 

#### Other Departure Climbs

screenshot 25

SKORR# departures require a similar hard left turn after takeoff and similar loss of separation will occur. (DEEZZ# departures follow SKORR# climbouts nearly identically, including hard left turns from **31L** and **31R**).

### After Climbout

#### JFK# and SKORR#

Departures via these SIDS will exit (or "transition") in generally four directions. _In the real world, there are five so-called departure "gates", though since the WEST gate consists of only_ SBJ (Solberg) _and_ LANNA _, I felt it safe to leave it out. In addition, the gate has certain specifics to the way aircraft are vectored to it and I felt it unnecessary to figure out how to incorporate those two transitions into the simulation._ The four directions are 
- SOUTH 1 (southeast of the field):
  - ARD (Yardley),
  - RBV (Robinsville),
  - RNGRR ("ranger" or "rain-jer"),
  - DIXIE, and
  - WHITE;
- SOUTH 2 (southwest, over the ocean):
  - WAVEY ("wave-ee"),
  - SHIPP,
  - HAPIE ("happy"), and
  - BETTE ("bet-ee");
- EAST (northeast of the field):
  - BDR (Bridgeport),
  - BAYYS ("bays"),
  - MERIT ("mare-it"), and
  - GREKI (I've heard "greek-ee" and "greck-ee");
- and NORTH (northwest of the field):
  - SAX (Sparta),
  - DEEZZ (like the SID),
  - GAYEL ("gale" or "gail" or "gay-ell"),
  - HAAYS ("hays" or "haze"),
  - NEION ("neon" or "nee-on"), and
  - COATE ("coat").

#### DEEZZ#

DEEZZ# has its own transitions: CANDR ("can-der") and TOWIN ("tou-in"; rhymes with "now in"). It follows the same climbout as SKORR# but instead of departing through a particular gate, aircraft are radar-vectored to DEEZZ where they then rejoin the published RNAV route (DEEZZ..HEERO ["hero"]..KURNL ["ker-nul" or "kernel" {or "colonel"}]..CANDR..TOWIN*).

In brief, once you `caf`, everything should be good to go. Here's a rough guide to where aircraft go after climbout:

screenshot 26

### What I do

With this configuration, I prefer using **31L** as my dedicated departure runway. If things get particularly busy, I will use **4L** for departures, assigning DEEZZ# for SIDS `W 4L SID DEEZZ4 CAF CVS`, and staggering them with **31L** to prevent incursions. Alternatively, I sometimes use **31R** as an overflow runway, however, this forces me to stagger departures with **31L** (not to mention arriving aircraft).

## Arrivals

KJFK accepts arriving traffic via six STARS: PARCH# ("parch" #), ROBER# ("row-bur" or "roe-bur" #), CAMRN# ("cam-ren" #), IGN# (Kingston; "Kings-ston" #), PWL# (PWL; "paw-ling" #), and LENDY# ("len-dee" #).

### LENDY# and IGN#

LENDY# and IGN# handle traffic from the North and West (e.g., Cleveland, Montreal). The important thing about them is that their last leg takes them along a route from LENDY to LGA (the VOR/DME) at FL190 and 250 kts. I usually split the flows so that LENDY# arrivals turn immediately south (heading 180-190 or direct COL [Colt's Neck]). I also descend this traffic to somewhere intermediate (like 5,000 ft) until closer in at which point I'll descend them to 3,000 ft to join the flow with CAMRN# traffic. IGN# traffic, I leave them on course but descend them to something like 6,000 ft until they're past the field. Then, I descend them to 4,000 ft to join ROBER# arrivals.

### CAMRN#

CAMRN# handles nearly all traffic from the South (e.g., San Juan, Atlanta). Arrivals will enter at 9,000 ft and 250 kts. Your best bet is to get them down to at least 4,000 ft as soon as you can so you don't have to worry about them. Sometimes I overflow arrivals onto **4R** when things get especially busy. CAMRN# arrivals are very easy to vector there, as well as LENDY# traffic. Once closer in to the airport, I get arrivals down to 2,000 ft if landing **31L** and if needed, 3,000 ft for **31R**.

### ROBER#, PARCH#, and PWL#

ROBER# and PARCH# are essentially identical. They handle the vast majority of incoming European, New England, and Middle Eastern traffic (e.g., London, Boston). These arrivals come in crossing ROBER at 9,000 ft and 250 kts. I tweaked the routing after ROBER as follows:
- for ROBER# arrivals:
  - ROBER, direct DEERY, cross DEERY at and maintain 4,000 [ft], speed 230 [kts]. Thence, direct DEUCE at and maintain 210 [kts].
- for PARCH# arrivals:
  - ROBER, direct JFK, crossing JFK at 4,000 [ft], speed not exceeding 250 [kts]. _This is the published routing (no change)._

Once these arrivals come into the airspace, I try to get them to 3,000 ft or 4,000 ft and spaced enough for me to be able to leave them alone. Depending on how "extended" I have the **31R** final leg, I will either route them direct CATOD (I've heard "kay-tod" and "cat-tod"), direct MALDE ("mall-dee"), direct ZULAB ("zoo-lab") `route CATOD..MALDE..ZULAB` or `rr CATOD..MALDE..ZULAB`. This works when I have a relatively short final leg; however, if the final is long, I just assign a southwest heading (heading 210-250) `fh220` and turn them towards the field when I need them to. Additionally, if I can't fit in an arrival and have to move it to **31L**, I descend it to 2,000 ft to discriminate it from other **31R** arrivals.

PWL# is only used by prop/turboprop aircraft operating at 250 kts or less. Arrivals come in descending to 4,000 ft, direct DPK (Deer Park), crossing at 210 kts. After DPK, they will proceed direct DEUCE at 4,000 ft, 210 kts. _This portion (direct DEUCE) is different than published._ These arrivals are pretty straightforward--all you have to do is watch for them and join them in with the IGN# arrivals and then ROBER# arrivals.

31lr arr

## Summary

In summary, I like to divvy up arrival flows between runways. To better organize them, I descend **31L** arrivals to 2,000 ft and **31R** arrivals to 3,000 ft. The wind permits overflows onto _either_ the 22s (preferably, **22L**) _or_ the 4s (preferably **4R**). A **31L**/**31R** arrival + **31L** departure configuration favors arrivals, so might not be preferable during the beginning of the simulation. As such, departures are favored using
- **31L** and **4R** or **22L** (equivalent)
  - _No runway conflicts, though pay attention to loss of separation when departing **22L**_
- **31L** and **4L**
  - _Alternating departures so that intersecting traffic does not conflict. **4R** for arrivals is best for this configuration so that there is less interdependence on arrivals/departures on other runways_
- **31L** and **31R**
  - _Alternating departures so that adequate spacing is maintained during climbout_.

During heavy arrival pushes,
- **31L** and **31R**
  - _**31L** departures dependent on arrivals_
- **31R** and **4R**
  - _Caution crossing departure traffic; you might have to issue departure altitudes to ensure proper vertical separation_
- **31R** and **31L** and **4R**
  - _Lots of moving parts_
- **31R** and **4L** and **4R**
  - _Ensure proper separation between arriving traffic (stagger it). **4L** missed approaches fly heading 100 `fh100` and **4R** missed approaches fly heading 140 `fh140` to maintain adequate separation after go-around_.

These configurations are useful to know, especially when traffic becomes extremely hectic. That way, you won't be wasting time thinking about how the setup should occur. Though, the time you spent reading this probably outweighs any time you could be playing the game.

**Comment by doofus** [comment]
This an excellent write-up on your changes.  What did you use to generate the last map?  Do you have any other insights regarding traffic management for other airports?

**Comment by jpeterson1346** [comment]
@doofus Thanks! And sorry for not citing my sources. That map was created by FAA's Traffic Flow Management team: [NY Airspace Map](http://tfmlearning.fly.faa.gov/NY_Airspace/NY_Airspace_Pkg/NY_Airspace.swf). It is slightly outdated but very useful nonetheless! I also wish they had those airspace flow maps for other airports too.

As far as other traffic "insights," I am most knowledgeable with KJFK. Additionally, though, I am familiar with the other NY Mets (and N90 TRACON), DC Mets (PCT), KDFW (and D10 TRACON), KORD (A90 TRACON), and KLAX (SCT). The main thing is that many TRACONs use the standard cornerpost arrivals/NSEW departures configuration for their airspace. A prime example is D10 (as well as A90):

### D10 TRACON (Dallas/Fort Worth)

#### Arrivals

Arriving traffic enters through one of four "cornerposts":
- BYP (Bonham; "bon-am"), _NORTHEAST_
- CQY (Cedar Creek), _SOUTHEAST_
- JEN (Glen Rose), _SOUTHWEST_ and
- UKW (Bowie; "boo-ee") _NORTHWEST_.

JEN traffic is usually pretty light as arrivals would be coming from the southwest. CQY traffic is usually second lightest, though a significant amount of Gulf traffic and Caribbean traffic arrives through this gate (e.g., Houston, Miami). BYP and UKW are usually the heaviest two gates as traffic arriving through them is usually coming from the North and East (e.g., Chicago, London) and the West (e.g., Los Angeles, Tokyo), respectively.

What's useful about this setup is that there is great flexibility and interchangeability with cornerpost arrivals. For instance, if (like today, 7 November at the time of this post), **_nearly_ ALL** traffic destined to KDFW (and KDAL) is subject to enroute restrictions. This is achieved through broad, national-level traffic initiatives and, in short, traffic affected by those initiatives are required to fly a certain defined route. The specifics are beyond the scope of this section, but basically, traffic that would normally or was previously scheduled (through their flightplans) to enter D10's airspace through the two northern cornerposts (BYP and UKW) face restrictions. As a result, affected arriving traffic is often routed so that they enter at other, less- or non-affected cornerposts. In this case, I imagine D10 is closing or restricting (by reducing the amount of arrivals they are willing to accept) BYP (northeast-inbound) traffic and forcing them to enter through CQY (southeast cornerpost). Likewise, I imagine UKW-bound traffic is being reduced and/or rerouted through JEN (southwest cornerpost). In any case, there is rather good flexibility for arriving traffic with this setup, mostly due to the extensive lateral and vertical availability of airspace--something which N90 generally lacks.

d10 setup
_Source: [FAA/NWS Center Weather Service Unit (CWSU) ZFW (Fort Worth Center)](http://www.weather.gov/images/zfw/rtimages/CornerWind.png) edited by me_

#### Departures

You may have guessed this but if arrivals enter via cornerposts, then departing traffic should exit in between, right? Absolutely. Departures exit through one of four cardinal directions. Similar to the flexibility to tactically and strategically redirect/reroute/restrict/etc. inbound cornerpost arrivals, departures can be managed analogously. Continuing with today's current situation, BYP and UKW are experiencing weather hazards which are affecting arrival traffic through those gates. Likewise, northbound departures are encountering those same hazards and are being restricted accordingly:

dfw n impacts
_Source: [FAA/NWS Center Weather Service Unit (CWSU) ZFW (Fort Worth Center)](http://www.weather.gov/zfw/gate_forecast)_

### KDFW Airport

#### Operations

##### Flow Configuration

KDFW operates in basically one of two configurations depending on wind and weather. These are **NORTH Flow** and **SOUTH Flow**. Occasionally, when weather is particularly ugly, KDFW is forced into the dreaded _**NORTHWEST Flow**_.

###### SOUTH Flow

SOUTH Flow is when traffic, arriving or departing, is directed _from_ North of the airport _to_ South of the airport (i.e., traffic is _flow_ing _SOUTH_). The preferred runway configuration is
- **17R**, **18L**, and **13L** for departures,
  - _This allows for a shorter taxi for departures since **17R** and **18L** are closest to the terminals_
- **18R**, **17C**, **17L**, and **13R** for arrivals.
  - _Thanks KDFW for all your amazing, non-intersecting, long runways!_

SOUTH Flow is essentially the default configuration and most common one for KDFW, unless the tailwind is greater than 5 kts. Then, KDFW goes into NORTH Flow...

###### NORTH Flow

NORTH Flow is basically opposite of SOUTH Flow:
- **35L**, **36R**, and **31L** for departures,
  - _This forces longer taxi times for departures, especially for **31L**, hence why SOUTH Flow is the preferred configuration_
- **36L**, **35C**, **35R**, and **31R** for arrivals.

##### Summary

In either flow, the 13s'/31s' arrivals force interdependence of them on 18s' and 17s'/35s' and 36s' departures, respectively. As such, it is most common to stick to the _**5**_ parallels for arrivals/departures to avoid such conflicts. _Further, in real world, arrivals on the 3 eastern-most runways in NORTH Flow (**17L**, **17C**, and **31R**) cause surface congestion on the East side taxiways. Luckily, this is not an issue for this simulation._ The use of multiple parallel runways (plus optionally non-intersecting diagonal runways) affords a high AAR (airport acceptance/arrival rate). Optimal conditions permit AAR of 120, though slightly higher than that is possible and common. When NORTHWEST Flow forces use of the 31s for arrivals and departures, AAR drops to well below half of optimal--generally 50 to sometimes 30 per hour. At its current state, weather is not a factor for ATC operations, however, possible future development may allow for such variables.

dfw configs
_Source: [VATSIM/VATUSA/ZFWARTCC (online virtual air traffic control organization)](https://www.dropbox.com/sh/ch9774k28vtgtdo/AADoqmB9iyubp2_w6stbmjJ4a/ARTCC%20Library/Controller%20Aids/D10?dl=0&preview=KDFW+Directional+Departures.png#) edited by me_

As far as traffic patterns go, KDFW has about a half-million SIDs and another half-million STARs. Luckily, nearly all of these are RNAV and thus follow pre-defined waypoints, allowing for explicit configuration in the `kdfw.json` file (compared to `kjfk.json`, I would say KDFW has it easy). In any case, I am not familiar with them other than that they're essentially pattern procedures--that is, STARs generally follow routes from cornerpost to standard field pattern, whereby standard downwind, base, final configuration is thence utilized (either via radar vectors or RNAV procedure).  SIDs do essentially the same:
- **SOUTH Flow**
  - Departing...
    - SOUTH of the airport (e.g., to Austin, to Cancun)--pretty straightforward; just keep going
    - NORTH of the airport (e.g., to New York, to Seattle)--turn _RIGHT_ if departing on the West side of the airport (**18L**); turn _LEFT_ if departing on the East side of the airport (**17R**, **13L**)
  - Arriving...
    - Easy. See the flow diagram below
- **NORTH Flow**
  - Do the reverse

dfw south flow config
_Source: [FAA/NWS Center Weather Service Unit (CWSU) ZFW (Fort Worth Center)](http://www.weather.gov/zfw/gate_forecast) edited by me_

**Comment by Fechulo** [comment]
@jpeterson1346 Wow, all of this information is extremely useful! I actually created KDFW back in August, but due to the development of v3 it hasn't been merged yet. However you can try it on my [fork](https://fechulo.github.io/). I'm looking forward to playing at JFK after this is merged!

**Comment by jpeterson1346** [comment]
@Fechulo KATL is called Boston Logan in your airport-select screen.

**Comment by Fechulo** [comment]
@jpeterson1346 Ha, well that's interesting, hadn't even noticed it.

**Comment by jpeterson1346** [comment]
@Fechulo Oh, and at first glance, I think you might have to tweak your SIDs so that parallel departing traffic doesn't converge. I don't know the specifics for each SID but it should be relatively easy to make it so that climbouts are discriminated by departure runway! Nice video map, by the way.

**Comment by Fechulo** [comment]
@jpeterson1346 The KATL name problem should be fixed now. I'm not quite sure what you mean, the departures were implemented as described in the charts, so the climbout does change depending on the runway.

**Comment by jpeterson1346** [comment]
@Fechulo Hmm...well some (not all) departures on 18L will turn left (into 17R departing traffic) after takeoff...

**Comment by Fechulo** [comment]
@jpeterson1346 Let's look at the [ZACHH2](http://www.aircharts.org/data/view.php?id=9c7fd34f-0870-5d8d-9608-e7547ea2f900) Departure. In this scenario, aircraft departing from 18L will converge into the 17R departures, but this is reallistic. ATC in real life would probably not assign RWY 18L to aircraft departing to the East.

**Comment by jpeterson1346** [comment]
@Fechulo Ok! I believe you. Like I said, not familiar with all the departures etc. at KDFW. KJFK has only 3. KDFW has what, like 16?

**Comment by Fechulo** [comment]
@jpeterson1346 It's certainly a lot of SID's!
a lot

**Comment by jpeterson1346** [comment]
Man, look at HUBBARD. HUBBARD9. That's a lot of updates. Psh...(JFK3, DEEZZ4, SKORR3).

**Comment by Fechulo** [comment]
The O'Hare 2 Departure at KORD used to be O'Hare 9, but it wrapped back around to 1 and about a month ago it was updated again. Interestingly enough I can't seem to find any differences between the old version and the new update of the departure.

**Comment by erikquinn** [comment]
@fechulo it's probably just updates to the depicted obstructions and/or minimum climb rates, and other stuff not related to the actual routing. That'd be my guess!

**Comment by erikquinn** [comment]
@jpeterson1346 We are in the process of getting everything moved over to the new home of the simulator: [https://github.com/openscope/openscope](https://github.com/openscope/openscope). Would you be able to close and reopen this pull request at the new repository? All issues and pulls here will soon be closed, and I want to make sure this one ends up getting merged into the sim. 😄

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), and thus, all pull requests are being closed. If you would still like to see this merged into the simulator, please reopen the pull request at the new repo. Thank you!

Closing this PR.

**Pull request closed without merging**
