### PR TITLE
[ready & complete] WMPK, Penang International Airport, MYS

### PR DESCRIPTION
**Pull request by eliuuk**
Penang International Airport is a small international airport based in Penang, which is an extremely small island west of Malaysia. Hub for AirAsia, it's also a destination for many Asian international airlines such as SilkAir and Firefly. Malaysia Airlines also run cargo and domestic passenger services to here.

Originally my home town, I now reside in Leeds in the United Kingdom!

### CODE REVIEW

**Comment by erikquinn** [comment]
There seems to be something wrong with one of the SIDs, as there is an infrequent crash when the sim tries to look up the current waypoint for an aircraft. Perhaps the `VPG` SID should be removed, as it doesn't seem to do much. But I'm not sure what is causing this issue. I sometimes get a freeze when issuing `caf cvs w` to the departures as I always do when testing the SIDs.

**Comment by eliuuk** [comment]
@erikquinn I'll do more testing on this tonight and have a look, thanks!

**Comment by eliuuk** [comment]
I've done a little bit of testing just now, and I can't seem to reproduce this, but I've managed to somehow get an aircraft circling around VPG

**Comment by erikquinn** [comment]
Yeah, I've tried some more and can't get it again. It was hard to make happen, so isn't real concerning, and it may have _nothing_ to do with this pull either; it could be something in the code that happens at every airport under a very specific set of circumstances. I _did_ change the wind so it wasn't at a 90 degree angle though, which may have something to do with it.

**Pull request merged**
