### PR TITLE
Draw projected aircraft path

### LINKED ISSUE #132: Draw projected aircraft path when selected
One way to help plan aircraft movements is to see where an aircraft will go in future, based on the ATC commands that have been entered.

For example, in following multiple fixes:

waypoints

Or following a heading and landing (the track is brighter when ILS lock is expected to happen):

landing2

These are screenshots from a running prototype. Appreciate any comments or suggestions.

### PR DESCRIPTION
**Pull request by glangford**
Fixes #132

### CODE REVIEW

**Comment by zlsa** [comment]
I've changed the colors as well; magenta (IMO) stands out too much. I made the colors the same as the airplane (departure/approach), and made the line a bit thicker when ILS is locked.

**Comment by zlsa** [comment]
2015-08-15-08-21-31-am

**Comment by glangford** [comment]
I used magenta since that is the color used in cockpit nav displays, but the colors you substituted definitely look better!

**Comment by zlsa** [comment]
I didn't even know they had tracking (and prediction!) in cockpits yet. Thanks for all the work you've been doing.

**Comment by glangford** [comment]
Glad to help. In the nav displays, I meant for planned trajectory, guided by the Flight Management System. The preplanned track the autopilot will fly is magenta.

**Pull request merged**
