### PR TITLE
Update ksfo.json airlines

### PR DESCRIPTION
**Pull request by ghariman**
First time using github. But below is my update for ksfo.json to update the airline to be more realistic.

### CODE REVIEW

**Comment by zlsa** [comment]
Have you run a local server to test this yet?

**Comment by ghariman** [comment]
Hi Jon,

As I mentioned I am not a programmer.
So I do not know how to run my code on a local server. I wanted to try my ksfo.json but I did not know how to launch the ATC game using my updated code.

If you inform me how to go about doing this then I may try it out (now or maybe next time around when I make more suggestions). I am willing and eager to learn.

Is there a tutorial on how to do it?

I am hoping for the time being maybe you can test the code? All I did was change the section of the list of airlines. I hope it works well.

Thank you.

**Comment by ghariman** [comment]
Hi Jon,
As I mentioned I am not a programmer.So I do not know how to run my code on a local server. I wanted to try my ksfo.json but I did not know how to launch the ATC game using my updated code.
If you inform me how to go about doing this then I may try it out the next time I make any code suggestions. I am willing and eager to learn.
Is there a tutorial on how to do it?
I am hoping for the time being maybe you can test the code? All I did was change the section of the list of airlines. I hope it works well.
Regards,George Hariman

```
  From: Jon Ross <notifications@github.com>
```

 To: zlsa/atc atc@noreply.github.com 
Cc: ghariman ghariman@yahoo.com
 Sent: Friday, March 4, 2016 9:14 AM
 Subject: Re: [atc] Update ksfo.json airlines (#410)

Have you run a local server to test this yet?—

**Comment by zlsa** [comment]
To test this yourself, just start a webserver at the root of the atc project:

```
python3 -m http.server
```

on Linux. Then, just go to the address in a browser and make sure it loads without any errors in the developer console.

**Comment by ghariman** [comment]
Not sure if I will be able to do that. I don't have a Linux box. And again I am not a software programmer so I do not really know much on that front.
If you can test the changes I made that would be great...and will make KSFO more realistic in terms of airlines coming in/out of the airport.
Thank you.

**Comment by Fechulo** [comment]
@ghariman I've tested it and it doesn't work due to a missing comma on line 152. Otherwise it works well and I think it's worth adding more airlines to some airports in the game. However there's a big change coming up which will affect all airport files ( #404 ). I would suggest waiting until #404 is merged and then adding this modification.

**Comment by erikquinn** [comment]
@ghariman I just recently figured out how to run a local web server myself, it's actually not too bad, and a good idea if you plan to contribute improvements like this every now and again. :smiley:

I use XAMPP because it's easy, very much just install it and point it to the directory where you downloaded the "ATC" repository from github. Just in case you haven't done that, and we're just working directly on the github website, I also included a video for that.

[Github Forking & Cloning](https://youtu.be/XdhuWDdu-rk)
[XAMPP Web Hosting Tutorial](https://youtu.be/DFmPg_qWxA8)

Only trick to get the apache web server working with github repository is to go and [change the paths](http://stackoverflow.com/a/18903044/5774767) in apache's settings so it knows where to find the files: set that to the path of wherever you cloned your repository to (mine is at d:\src\atc for example). Then you just go to "localhost" in the browser and the game will load. Make any changes you want, refresh the page, and test them out live. It's really pretty sweet.

**Comment by ghariman** [comment]
@Fechulo: Thank you for catching the missing coma on line 152. Must have happened as I copied and pasted more lines to add more airlines. I fixed that error now.
By the way what are the "sa-airlines"? Could not find explanation on that.

@zlsa can make the decision to wait for #404 to be merged before merging this one or not. But if he can merged this one now that would be nice.

@erikquinn: This is great. I just watched the tutorial video on XAMPP. Very cool. I will try it out a bit later. If that works on my computer then I will definitely use it to test my code updates. In terms of the path, worst case is I can just keep copy/paste the whole repository folders to XAMPP's "htdocs" folder when testing/debugging. This is awesome. Thank you so much.

**Comment by Fechulo** [comment]
The sa- airlines were created by @MaicomMR to make sure that airports in Brazil wouldn't receive small aircraft from european airlines, as it wouldn't be realistic. This was not the most elegant solution and it has since been "fixed", however not all airlines have been updated yet.

**Comment by ghariman** [comment]
I figured out how to test my code without a local server.
I used ghariman.github.io and then I put my files there (the clone of ZLSA's ATC files) with my updated ksfo.json file.
So now if you go to: http://ghariman.github.io/
and play KSFO airport, it will show the updates that I made to the airlines.
I will use this method in the future to test my code prior to submitting a pull request.

**Comment by erikquinn** [comment]
@ghariman yep that works too. For those of us who are impatient with our technology (ahem, like me) just prefer local hosting because it can sometimes take 10 seconds for pushed changes to go live on github pages sites, and sometimes 3 MINUTES, whereas local web servers are updated instantly as soon aa you save the edited files. But yes, it works perfectly well. Another tip if you're using chrome: use incognito mode and press f12 to bring up the dev console, and from there you can right-click the refresh button and "flush cache and hard reload" (something like that) so you force the browser to fully re-download the page so you know you are testing with your latest changes, and not just the less recent version that is hanging around in the browser's cache.

**Comment by ghariman** [comment]
OK all, I made more updates: I added SHORELINE sid.
But I am going to update gh-pages directly and so I will close this pull request and create another one from gh-pages.

And here is where I test my code: http://ghariman.github.io/atc/

**Pull request closed without merging**
