### PR TITLE
[WIP] Flughafen München facelift

### PR DESCRIPTION
**Pull request by eliuuk**
München is Munich.
- [ ] Update STARs
- [ ] Revise traffic

If someone could assist with terrain, it'd be highly appreciated - my PC cannot handle the natural neighbour process.

### CODE REVIEW

**Comment by Fechulo** [comment]
@indianbhaji Unfortunately, I tried creating the terrain for München in the past, but due to some of the limitations of the current method for generating terrain, a lot of errors come up. I'll try again, but I don't think I'll be able to get it to work.

**Comment by eliuuk** [comment]
@Fechulo Alright, tell me the result, if it doesn't work, we'll just leave it. Thanks!

**Comment by erikquinn** [comment]
Is this still being held?

**Comment by Fechulo** [comment]
@erikquinn @indianbhaji To be honest, I haven't tried adding terrain since the last time, but I don't think I'll be able to make it work. The method we're using to generate the terrain works fine, but it's not perfect. Unfortunately, all of the imperfections of this method come up when trying to generate the terrain for EDDM.

**Comment by eliuuk** [comment]
This is actually held because I haven't finished all the SIDs due to my poor prioritisation.

**Comment by eliuuk** [comment]
Relocated to openscope/openscope#98, closing!

**Pull request closed without merging**
