### PR TITLE
Update ltba.json

### PR DESCRIPTION
**Pull request by gitsalty**
Updated fixes

### CODE REVIEW

**Comment by gitsalty** [comment]
Also and update to the whole .json with fixing Rwy placement and also placing SIDS (but im having issues forking it here)

**Comment by gitsalty** [comment]
{
  "radio": {
    "twr": "Istanbul Tower",
    "app": "Istanbul Approach",
    "dep": "Istanbul Departure"
  },
  "icao": "LTBA",
  "iata": "IST",
  "magnetic_north": 5.25,
  "ctr_radius": 80,
  "ctr_ceiling": 15000,
  "initial_alt": 5000,
  "position": ["N40.976898", "E28.814600", "163ft"],
  "rr_radius_nm": 5.0,
  "rr_center": ["N40.976898", "E28.814600"],
  "has_terrain": false,
  "wind": {
    "angle": 25,
    "speed": 6
  },
  "fixes": {
    "LTBA": ["N40.976898", "E28.814600"],
    "NORTH": ["N41.697227", "E28.814600"],
    "EAST" : ["N40.972989", "E29.765082"],
    "SOUTH": ["N40.256479", "E28.814600"],
    "WEST" : ["N40.972989", "E27.864118"],
    "IST": ["N41.057201", "E28.806400"],
    "CEK": ["N41.005798", "E28.528099"],
    "BKZ": ["N41.126900", "E29.142799"],
    "SBH": ["N40.899700", "E29.320400"],
    "YAA": ["N40.474998", "E29.207500"],
    "UNSAV": ["N41.479166", "E28.788666"],
    "ERTAS": ["N41.461666", "E29.145666"],
    "YASEN": ["N41.199000", "E29.515166"],
    "GAYEM": ["N41.046000", "E29.629500"],
    "ELGOV": ["N40.595166", "E28.016666"],
    "CRL": ["N41.150833", "E27.935000"],
    "IMREN": ["N40.765000", "E28.383333"],
    "SADIK": ["N40.678333", "E28.818333"],
    "ERMAN": ["N40.795000", "E28.815000"],
    "FATIH": ["N41.228666", "E28.799333"],
    "KOFUN": ["N41.060000", "E28.988333"],
    "ATCOS": ["N40.895000", "E28.633333"],
    "FENER": ["N41.288333", "E28.335000"],
    "TETSA": ["N41.733333", "E28.780000"],
    "EVNOT": ["N40.789333", "E29.616666"],
    "EKDAM": ["N40.435000", "E29.616666"],
    "DEKEK": ["N40.335000", "E29.323333"],
    "BRY": ["N40.263166", "E29.595833"],
    "TIRER": ["N41.141166", "E28.382333"],
    "UNTUT": ["N41.593333", "E28.683333"],
    "GEVLA": ["N40.990000", "E28.336666"],
    "ZEMBA": ["N40.950000", "E27.856666"],
    "RIMBO": ["N41.381666", "E28.551666"],
    "ERLEB": ["N41.121666", "E28.555000"],
    "TURKO": ["N40.649444", "E27.586667"]
  },
  "runways": [
    {
      "_reference":  "https://www.ourairports.com/airports/LTBA/pilot-info.html",
      "name":         ["35R", "17L"],
      "name_offset":  [[0, 0], [0, 0.4]],
      "end":    [ ["N40.969456", "E28.809469", "100ft"], ["N40.996358", "E28.808525", "157ft"] ],
      "angle":        354,
      "length":       3,
      "ils":          [true, true]
    },
    {
      "name":         ["35L", "17R"],
      "name_offset":  [[0, -0.2], [0, 0.4]],
      "end":    [ ["N40.969333", "E28.807000", "102ft"], ["N40.996333", "E28.806000", "163ft"] ],
      "angle":        354,
      "length":       3,
      "ils":          [true, true]
    },
    {
      "name":         ["23", "5"],
      "name_offset":  [[0, 0], [0, 0]],
      "end":    [ ["N40.977833", "E28.836167", "90ft"], ["N40.966333", "E28.811333", "93ft"]],
      "angle":        235,
      "length":       2.3,
      "ils":          [true, true]
    }
  ],
  "sids": {
    "YAA1": {
      "icao": "YAA1",
      "name": "Yalova One",
      "rwy": {
        "35L": ["BKZ", "YAA", "BRY"],
        "35R": ["BKZ", "YAA", "BRY"],
        "17L": ["BKZ", "YAA", "BRY"],
        "17R": ["BKZ", "YAA", "BRY"],
        "5" : ["BKZ", "YAA", "BRY"],
        "23" : ["BKZ", "YAA", "BRY"]
      },
      "draw": [["BRZ","YAA","BRY"]]
    },
    "ERTAS1": {
      "icao" : "ERTAS1",
      "name" : "Ertas One",
      "rwy": {
        "35L": ["BKZ", "ERTAS"],
        "35R": ["BKZ", "ERTAS"],
        "17L": ["BKZ", "ERTAS"],
        "17R": ["BKZ", "ERTAS"],
        "5" : ["BKZ", "ERTAS"],
        "23" : ["BKZ", "ERTAS"]
      },
      "draw": [["BKZ","ERTAS"]]
    },
    "BIG1": {
      "icao": "BIG1",
      "name": "Biga One",
      "rwy": {
        "35L": ["KOFUN", "CEK", "TURKO"],
        "35R": ["KOFUN", "CEK", "TURKO"],
        "17L": ["KOFUN", "CEK", "TURKO"],
        "17R": ["KOFUN", "CEK", "TURKO"],
        "5" : ["KOFUN", "CEK", "TURKO"],
        "23" : ["KOFUN", "CEK", "TURKO"]
      },
      "draw": [["KOFUN","CEK","TURKO"]]
    },
    "CRL1": {
      "icao": "CRL1",
      "name": "Corlu One",
      "rwy": {
        "35L": ["KOFUN", "CRL"],
        "35R": ["KOFUN", "CRL"],
        "17L": ["KOFUN", "CRL"],
        "17R": ["KOFUN", "CRL"],
        "5" : ["KOFUN", "CRL"],
        "23" : ["KOFUN", "CRL"]
      },
      "draw": [["KOFUN","CRL"]]
    },
    "FENER1": {
      "icao": "FENER1",
      "name": "Fener One",
      "rwy": {
        "35L": ["KOFUN", "FENER"],
        "35R": ["KOFUN", "FENER"],
        "17L": ["KOFUN", "FENER"],
        "17R": ["KOFUN", "FENER"],
        "5" : ["KOFUN", "FENER"],
        "23" : ["KOFUN", "FENER"]
      },
      "draw": [["KOFUN","FENER"]]
    }
  },
  "departures": {
    "destinations": [
       "YAA1", "ERTAS1", "BIG1", "CRL1", "FENER1"
    ],
    "type": "random",
    "frequency": 3.5,
    "airlines": [
      ["aca", 4],
      ["afl", 6],
      ["baw", 4],
      ["thy", 2],
      ["dal", 4],
      ["fdx", 7],
      ["klm", 5],
      ["ups", 8],
      ["fastga", 10],
      ["lightga", 11]
    ]
  },
  "arrivals": [
    {
      "radial":    90,
      "heading":   270,
      "altitude":  [6000, 9000],
      "speed": 250,
      "type": "random",
      "frequency": 8.5,
      "airlines":  [
        ["lightga", 11],
        ["afl", 6],
        ["fastga", 10]
      ]
    },
    {
      "radial":    180,
      "heading":   360,
      "altitude":  [5000, 7000],
      "speed": 250,
      "type": "random",
      "frequency": 9,
      "airlines":  [
        ["thy", 2],
        ["fdx", 7],
        ["lightga", 11]
      ]
    },
    {
      "radial":    270,
      "heading":   90,
      "altitude":  [7000, 9000],
      "speed": 250,
      "type": "random",
      "frequency": 7,
      "airlines":  [
        ["aca", 4],
        ["baw", 4],
        ["thy", 2],
        ["dal", 4],
        ["fdx", 7],
        ["klm", 5],
        ["fastga", 10]
      ]
    },
    {
      "radial":    360,
      "heading":   180,
      "altitude":  [5000, 8000],
      "speed": 250,
      "type": "random",
      "frequency": 12.5,
      "airlines":  [
        ["afl", 6],
        ["baw", 4],
        ["thy", 2],
        ["dal", 4],
        ["fdx", 7],
        ["klm", 5],
        ["ups", 8],
        ["fastga", 10]
      ]
    },
    {
      "radial":    180,
      "heading":   360,
      "altitude":  [3000, 5000],
      "speed": 250,
      "type": "random",
      "frequency": 15,
      "speed":     120,
      "airlines":  [
        ["lightga", 20]
      ]
    },
    {
      "radial":    45,
      "heading":   225,
      "altitude":  [7000, 9000],
      "speed": 250,
      "type": "random",
      "frequency": 12.5,
      "airlines":  [
        ["ups", 8],
        ["thy", 2],
        ["fastga", 20]
      ]
    },
    {
      "radial":    315,
      "heading":   135,
      "altitude":  [6000, 8000],
      "speed": 250,
      "type": "random",
      "frequency": 4,
      "airlines":  [
        ["afl", 6],
        ["baw", 4],
        ["thy", 2],
        ["dal", 4],
        ["fdx", 7],
        ["klm", 5],
        ["ups", 8],
        ["fastga", 10],
        ["aca", 4],
        ["lightga", 11]
      ]
    }
  ]
}

**Comment by gitsalty** [comment]
`{
  "radio": {
    "twr": "Istanbul Tower",
    "app": "Istanbul Approach",
    "dep": "Istanbul Departure"
  },
  "icao": "LTBA",
  "iata": "IST",
  "magnetic_north": 5.25,
  "ctr_radius": 80,
  "ctr_ceiling": 15000,
  "initial_alt": 5000,
  "position": ["N40.976898", "E28.814600", "163ft"],
  "rr_radius_nm": 5.0,
  "rr_center": ["N40.976898", "E28.814600"],
  "has_terrain": false,
  "wind": {
    "angle": 25,
    "speed": 6
  },
  "fixes": {
    "LTBA": ["N40.976898", "E28.814600"],
    "NORTH": ["N41.697227", "E28.814600"],
    "EAST" : ["N40.972989", "E29.765082"],
    "SOUTH": ["N40.256479", "E28.814600"],
    "WEST" : ["N40.972989", "E27.864118"],
    "IST": ["N41.057201", "E28.806400"],
    "CEK": ["N41.005798", "E28.528099"],
    "BKZ": ["N41.126900", "E29.142799"],
    "SBH": ["N40.899700", "E29.320400"],
    "YAA": ["N40.474998", "E29.207500"],
    "UNSAV": ["N41.479166", "E28.788666"],
    "ERTAS": ["N41.461666", "E29.145666"],
    "YASEN": ["N41.199000", "E29.515166"],
    "GAYEM": ["N41.046000", "E29.629500"],
    "ELGOV": ["N40.595166", "E28.016666"],
    "CRL": ["N41.150833", "E27.935000"],
    "IMREN": ["N40.765000", "E28.383333"],
    "SADIK": ["N40.678333", "E28.818333"],
    "ERMAN": ["N40.795000", "E28.815000"],
    "FATIH": ["N41.228666", "E28.799333"],
    "KOFUN": ["N41.060000", "E28.988333"],
    "ATCOS": ["N40.895000", "E28.633333"],
    "FENER": ["N41.288333", "E28.335000"],
    "TETSA": ["N41.733333", "E28.780000"],
    "EVNOT": ["N40.789333", "E29.616666"],
    "EKDAM": ["N40.435000", "E29.616666"],
    "DEKEK": ["N40.335000", "E29.323333"],
    "BRY": ["N40.263166", "E29.595833"],
    "TIRER": ["N41.141166", "E28.382333"],
    "UNTUT": ["N41.593333", "E28.683333"],
    "GEVLA": ["N40.990000", "E28.336666"],
    "ZEMBA": ["N40.950000", "E27.856666"],
    "RIMBO": ["N41.381666", "E28.551666"],
    "ERLEB": ["N41.121666", "E28.555000"],
    "TURKO": ["N40.649444", "E27.586667"]
  },
  "runways": [
    {
      "_reference":  "https://www.ourairports.com/airports/LTBA/pilot-info.html",
      "name":         ["35R", "17L"],
      "name_offset":  [[0, 0], [0, 0.4]],
      "end":    [ ["N40.969456", "E28.809469", "100ft"], ["N40.996358", "E28.808525", "157ft"] ],
      "angle":        354,
      "length":       3,
      "ils":          [true, true]
    },
    {
      "name":         ["35L", "17R"],
      "name_offset":  [[0, -0.2], [0, 0.4]],
      "end":    [ ["N40.969333", "E28.807000", "102ft"], ["N40.996333", "E28.806000", "163ft"] ],
      "angle":        354,
      "length":       3,
      "ils":          [true, true]
    },
    {
      "name":         ["23", "5"],
      "name_offset":  [[0, 0], [0, 0]],
      "end":    [ ["N40.977833", "E28.836167", "90ft"], ["N40.966333", "E28.811333", "93ft"]],
      "angle":        235,
      "length":       2.3,
      "ils":          [true, true]
    }
  ],
  "sids": {
    "YAA1": {
      "icao": "YAA1",
      "name": "Yalova One",
      "rwy": {
        "35L": ["BKZ", "YAA", "BRY"],
        "35R": ["BKZ", "YAA", "BRY"],
        "17L": ["BKZ", "YAA", "BRY"],
        "17R": ["BKZ", "YAA", "BRY"],
        "5" : ["BKZ", "YAA", "BRY"],
        "23" : ["BKZ", "YAA", "BRY"]
      },
      "draw": [["BRZ","YAA","BRY"]]
    },
    "ERTAS1": {
      "icao" : "ERTAS1",
      "name" : "Ertas One",
      "rwy": {
        "35L": ["BKZ", "ERTAS"],
        "35R": ["BKZ", "ERTAS"],
        "17L": ["BKZ", "ERTAS"],
        "17R": ["BKZ", "ERTAS"],
        "5" : ["BKZ", "ERTAS"],
        "23" : ["BKZ", "ERTAS"]
      },
      "draw": [["BKZ","ERTAS"]]
    },
    "BIG1": {
      "icao": "BIG1",
      "name": "Biga One",
      "rwy": {
        "35L": ["KOFUN", "CEK", "TURKO"],
        "35R": ["KOFUN", "CEK", "TURKO"],
        "17L": ["KOFUN", "CEK", "TURKO"],
        "17R": ["KOFUN", "CEK", "TURKO"],
        "5" : ["KOFUN", "CEK", "TURKO"],
        "23" : ["KOFUN", "CEK", "TURKO"]
      },
      "draw": [["KOFUN","CEK","TURKO"]]
    },
    "CRL1": {
      "icao": "CRL1",
      "name": "Corlu One",
      "rwy": {
        "35L": ["KOFUN", "CRL"],
        "35R": ["KOFUN", "CRL"],
        "17L": ["KOFUN", "CRL"],
        "17R": ["KOFUN", "CRL"],
        "5" : ["KOFUN", "CRL"],
        "23" : ["KOFUN", "CRL"]
      },
      "draw": [["KOFUN","CRL"]]
    },
    "FENER1": {
      "icao": "FENER1",
      "name": "Fener One",
      "rwy": {
        "35L": ["KOFUN", "FENER"],
        "35R": ["KOFUN", "FENER"],
        "17L": ["KOFUN", "FENER"],
        "17R": ["KOFUN", "FENER"],
        "5" : ["KOFUN", "FENER"],
        "23" : ["KOFUN", "FENER"]
      },
      "draw": [["KOFUN","FENER"]]
    }
  },
  "departures": {
    "destinations": [
       "YAA1", "ERTAS1", "BIG1", "CRL1", "FENER1"
    ],
    "type": "random",
    "frequency": 3.5,
    "airlines": [
      ["aca", 4],
      ["afl", 6],
      ["baw", 4],
      ["thy", 2],
      ["dal", 4],
      ["fdx", 7],
      ["klm", 5],
      ["ups", 8],
      ["fastga", 10],
      ["lightga", 11]
    ]
  },
  "arrivals": [
    {
      "radial":    90,
      "heading":   270,
      "altitude":  [6000, 9000],
      "speed": 250,
      "type": "random",
      "frequency": 8.5,
      "airlines":  [
        ["lightga", 11],
        ["afl", 6],
        ["fastga", 10]
      ]
    },
    {
      "radial":    180,
      "heading":   360,
      "altitude":  [5000, 7000],
      "speed": 250,
      "type": "random",
      "frequency": 9,
      "airlines":  [
        ["thy", 2],
        ["fdx", 7],
        ["lightga", 11]
      ]
    },
    {
      "radial":    270,
      "heading":   90,
      "altitude":  [7000, 9000],
      "speed": 250,
      "type": "random",
      "frequency": 7,
      "airlines":  [
        ["aca", 4],
        ["baw", 4],
        ["thy", 2],
        ["dal", 4],
        ["fdx", 7],
        ["klm", 5],
        ["fastga", 10]
      ]
    },
    {
      "radial":    360,
      "heading":   180,
      "altitude":  [5000, 8000],
      "speed": 250,
      "type": "random",
      "frequency": 12.5,
      "airlines":  [
        ["afl", 6],
        ["baw", 4],
        ["thy", 2],
        ["dal", 4],
        ["fdx", 7],
        ["klm", 5],
        ["ups", 8],
        ["fastga", 10]
      ]
    },
    {
      "radial":    180,
      "heading":   360,
      "altitude":  [3000, 5000],
      "speed": 250,
      "type": "random",
      "frequency": 15,
      "speed":     120,
      "airlines":  [
        ["lightga", 20]
      ]
    },
    {
      "radial":    45,
      "heading":   225,
      "altitude":  [7000, 9000],
      "speed": 250,
      "type": "random",
      "frequency": 12.5,
      "airlines":  [
        ["ups", 8],
        ["thy", 2],
        ["fastga", 20]
      ]
    },
    {
      "radial":    315,
      "heading":   135,
      "altitude":  [6000, 8000],
      "speed": 250,
      "type": "random",
      "frequency": 4,
      "airlines":  [
        ["afl", 6],
        ["baw", 4],
        ["thy", 2],
        ["dal", 4],
        ["fdx", 7],
        ["klm", 5],
        ["ups", 8],
        ["fastga", 10],
        ["aca", 4],
        ["lightga", 11]
      ]
    }
  ]
}`

**Comment by erikquinn** [comment]
@gitsalty We are in the process of getting everything moved over to the new home of the simulator: [https://github.com/openscope/openscope](https://github.com/openscope/openscope). Would you be able to close and reopen this pull request at the new repository? All issues and pulls here will soon be closed, and I want to make sure this one ends up getting merged into the sim. 😄

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), and thus, all pull requests are being closed. If you would still like to see this merged into the simulator, please reopen the pull request at the new repo. Thank you!

Closing this PR.

**Pull request closed without merging**
