### PR TITLE
v3.0.0

### PR DESCRIPTION
**Pull request by n8rzz**
This is a re-target of a previous WIP PR #679.  This is now targeting the correct branch from by fork.  For previous PR notes, see #679.

Current progress can be seen at: [https://n8rzz.github.io/atc](https://n8rzz.github.io/atc)
Bugs can be reported at: [http://github.com/n8rzz/atc/issues](http://github.com/n8rzz/atc/issues)

If you want to tackle a bugfix yourself:
- branch off of `release/3.0.0` and title your bugfix branch `bugfix/ATC-{ISSUE_NUMBER}` where {ISSUE_NUMBER} is the specific issue reported.
- be sure your commit messages are prepended with `bugfix/ATC-{ISSUE_NUMBER}` and are descriptive.
- Open a PR targeting `release/3.0.0` for review when the issue is complete and assign it to one of the participants of my fork.

### CODE REVIEW

**Comment by erikquinn** [comment]
@n8rzz this is now complete, yes?

**Comment by n8rzz** [comment]
Ship it!!

**Comment by erikquinn** [comment]
@doofus @fechulo @ghariman @indianbhaji @jakobeng1303 @lachsschinken124 @jpeterson1346 @kaitsu @luznicky @siyuanr @willfrd

...and any others who regularly play the game: throughout this week, when you play, please do so on the demo of the upcoming new version, which can be played here:

### [https://n8rzz.github.io/atc](https://n8rzz.github.io/atc)

Keep an eye out for anything that seems strange. If you notice anything that was broken by these new changes, please write up an issue about it. As long as there are no significant findings, these changes will be pushed live _this Saturday, November 12th at 2200z_, and minor problems will be addressed at a later date.

Thanks for your help; completing these changes means new features are becoming closer on the horizon!

EQ

**Comment by doofus** [comment]
Do you want issues reported here on your fork?

**Comment by n8rzz** [comment]
@doofus add an issue here so its all in one place and everybody else can see.  I will likely add another issue on my fork that references the original, but that is merely for my own tracking purposes.

**Comment by luznicky** [comment]
Hi,
spent about an hour on LKPR, and only found "cleared to take off, already taking off" bug, which is already addressed in another issue.

Looking forward to new features. Thx guys.

**Comment by erikquinn** [comment]
Despite some minor issues that have come up with localizer interception, this will now be merged. A fix will be put out once the wiggling can be removed from the process of aircraft joining the localizer. For most normal clearances, where a 30 degree intercept angle or less is used, there is no issue; as the intercept angle increases it becomes noticeable, but even still they still will eventually establish, despite the projection lines looking all crazy.

Thanks to everybody for searching for issues, I'm glad everything remains intact. And of course an enormous thank you to @n8rzz for all the time and effort he's put into these changes. They will make an immeasurable difference in moving the project forward!

Merging.

**Comment by n8rzz** [comment]
Yes, thank you to everybody that helped testing v3!  Also thanks to @erikquinn and the other contributors on this project for letting me come in and make some changes.  Its been a lot of fun so far!

Now that this is merged, my fork will represent v3.1.0 work.  There is _much_ more to come!!

**Comment by bvanvelsen** [comment]
when playing the n8rzz version I still get the false-positive penalty when intercepting localizer when perfectly lining up with the runway.

**Pull request merged**
