### PR TITLE
Implement select all aircraft, fixes #175

### LINKED ISSUE #175: Select all airplanes.
I would like to implement a way to select all airplanes. This way you can see what every airplane is doing and if they are going to cross each other. I came across this when i type in a letter some airplanes will be selected including a picture of where they are heading and going. I would like to add a command which shows the path of all airplanes! We could use the word "all" to highlight all airplanes.

schermafbeelding 2015-09-10 om 14 09 53

As you can see, 3 airplanes are selected, but i would like to see a new function where you can select all airplanes!

I would like to have some thoughts about this! Let me know

### PR DESCRIPTION
**Pull request by glangford**
All aircraft can be selected (and their future tracks can be viewed) by entering '*'.

### CODE REVIEW

**Comment by nielsvdweide** [comment]
Still waiting for this haha!

**Comment by zlsa** [comment]
Completely missed this, sorry!

**Comment by glangford** [comment]
@zlsa - I see the merged code in the branch, but not running in the live version. Is it possible that github pages at http://zlsa.github.io/atc/ are somehow not sync'd to the gh-pages branch?

**Comment by zlsa** [comment]
Hm, that should work. I have no idea why it's not... I'm looking into it now.

**Comment by zlsa** [comment]
Fixed. I just updated the version number and pushed that.

**Comment by glangford** [comment]
Perfect, thanks!

**Pull request merged**
