### PR TITLE
Added some fixes at LOWW

### PR DESCRIPTION
**Pull request by maebruck**
Added some fixes at LOWW

### CODE REVIEW

**Comment by maebruck** [comment]
Reopened pull request although some fixes are outside of loww airspace, they are needed for SIDs und STARs

**Comment by erikquinn** [comment]
@lachsschinken124 Unless we are actually using these fixes for something, to be hoenst, this only seems to add clutter at an airport that already has an extremely high number of depicted fixes... I believe @Fechulo originally had all of these fixes in there, and removed the ones that weren't needed for this exact reason.

If you want to add the SIDs/STARs that use these fixes, it may be worth adding... But for now, I'm afraid I don't personally see how adding _just the fixes_ by themselves is really an improvement.

### Current:

before

### Proposed:

after

**Comment by Fechulo** [comment]
@erikquinn as far as I know, I've added all the SID's, so I doubt those fixes are for SID's. I would personally keep the new fixes for STAR's (eg, WW191 and WW192), but I don't really see the point of having more unnecessary fixes.

**Comment by erikquinn** [comment]
@Fechulo Okay, I see. And yeah, if the fixes come with STARs, I have no problems merging them. But each fix that's added needs to have a purpose, as we've already got quite a few.

**Comment by Fechulo** [comment]
> quite a few.

lol. In fact, There's many more fixes for the STAR's that could be added, which wouldn't clutter the airspace.

**Comment by maebruck** [comment]
I'll close this pull request for now

**Pull request closed without merging**
