### PR TITLE
Update airport.js

### PR DESCRIPTION
**Pull request by gitsalty**
In accordance to #205, #206, and #208. Cross fingers this doesn't break.

### CODE REVIEW

**Comment by glangford** [comment]
@gitsalty - almost there, but there are still a few issues to correct. The file format for defining airports is picky, and LTBA doesn't load correctly yet.

If you make these changes then push to your patch-1 branch, this pull request will automatically update:
- Remove the leading zero from the wind angle ("025")
- Remove the blank line that is just after "fixes"

**Comment by gitsalty** [comment]
@glangford Thank you for the advice and help! Fixed the issues mentioned.

**Comment by glangford** [comment]
:+1: 

@gitsalty Glad to help! In future, what you want to do is fully test your changes before submitting the pull request. You can do this for example by simply opening your copy of the project index.html in your browser.

**Comment by zlsa** [comment]
Merged.

**Pull request closed without merging**
