### PR TITLE
New Airport: KORD (Chicago O'Hare Intl.)

### PR DESCRIPTION
**Pull request by Fechulo**
The video map would not be there if it weren't for @erikquinn, so thank you :smile:! It seems like it's not too laggy if the fixes and SID's are disabled. (Although my computer is pretty beefy so others may experience more lag). You can take a look at it [here](https://fechulo.github.io/)!

### CODE REVIEW

**Comment by eliuuk** [comment]
Perfectly fine for me, well done!

**Comment by Fechulo** [comment]
@indianbhaji Thanks! Did you have any performance issues?

**Comment by eliuuk** [comment]
@Fechulo Not at all, as much as I have a crap PC with only 3GB RAM, I've made it through so far! :+1:

**Comment by Fechulo** [comment]
Great news then! Thanks for the feedback

**Pull request merged**
