### PR TITLE
Glossary Start

### PR DESCRIPTION
**Pull request by ghost**
Started on what @n8rzz suggested in https://github.com/n8rzz/atc/issues/247

### CODE REVIEW

**Comment by n8rzz** [comment]
@TheMikeyLaw I would encourage you to write this in markdown so that it can be formatted and view directly from source.  A current example is the readme located in the tools folder https://github.com/zlsa/atc/tree/gh-pages/tools

Markdown is pretty easy to learn, if you are unfamiliar. 
- https://guides.github.com/features/mastering-markdown/
- https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

Additionally, and I'll leave this up to @erikquinn, you might be better served doing this work within my fork.  That way I will be able to provide PR feedback inline and approve any merge request.  Be sure to read the [git-flow documentation](https://github.com/n8rzz/atc/blob/gh-pages/tools/documentation/git-flow-process.md) and create a new feature branch if you do.  Then push directly to my fork and open a PR there.

Either way, this documentation is sorely needed and any work you can do here is greatly appreciated!

**Comment by ghost** [comment]
@n8rzz Yeah I'll put it into markdown. I will be happy to do it in any fork it's needed, let me know

**Comment by n8rzz** [comment]
@TheMikeyLaw right on.  Yeah, go ahead and move this over to my fork, I've added you as a contributor.  Be sure to make a fresh clone of my the `develop` branch and then create a feature branch from there.  when you open the PR, target `develop`.  You can open a PR at any time.

Feel free to reach out if you get stuck, have questions, or need anything else.

Thanks!!

**Comment by erikquinn** [comment]
Sounds like a good plan to me!

Welcome to the dark side, @TheMikeyLaw :wink:

**Comment by erikquinn** [comment]
@themikeylaw We are in the process of getting everything moved over to the new home of the simulator: [https://github.com/openscope/openscope](https://github.com/openscope/openscope). Would you be able to close and reopen this pull request at the new repository? All issues and pulls here will soon be closed, and I want to make sure this one ends up getting merged into the sim. 😄

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), and thus, all pull requests are being closed. If you would still like to see this merged into the simulator, please reopen the pull request at the new repo. Thank you!

Closing this PR.

**Pull request closed without merging**
