### PR TITLE
Remove "-sa" Airlines

### PR DESCRIPTION
**Pull request by MaicomMR**
This Pull want to kill my horrible creation, the "sa-" airlines, At create this airlines not have the new default mode(90default, 90long, Default, Long) to put airlines fleet in groups. On this Pull I delete all the "-sa" and replace this names in airport files to the correct way.

### CODE REVIEW

**Comment by MaicomMR** [comment]
Cc @zlsa

**Comment by MaicomMR** [comment]
@erikquinn or @zlsa please check this pull.

**Comment by erikquinn** [comment]
@MaicomMR I had a look yesterday, but didn't get to it because some of these changes conflict with existing code in the repository. I was able to resolve most of them, but there is one remaining issue I would need you to resolve:

The newly added aircraft do not have all of the properties they need. Airlines spawning these aircraft are crashing the game because certain parts of the code are trying to use parameters that these new aircraft don't have. The problem files are `b741.json`, `md83.json`, `md87.json`, and `md88.json`. I'd recommend copying the contents of an existing aircraft json, such as `b738.json`, and replace the values with the correct numbers for each of your new aircraft.

Beyond that, everything looks good to go, but I can't give it a thorough and proper test until the aircraft are fixed. Sorry, It's just kind of tough because this pull request is based off of an old version of the repo, so it isn't as easy as it usually would be. Let me know when this has the updates done, and I'll get back to reviewing it.

**Comment by MaicomMR** [comment]
This request is stopped a long time, unfortunately not pull it before, the standards already have changed, I will make the necessary changes again.
Hugs

**Comment by MaicomMR** [comment]
@erikquinn I fix the new airplanes(b741, md83, md87, md88 and b742 too) ~~but maybe i need to learn more about the SRS(Same Runway Separation) and the LAHSO(LAND AND HOLD SHORT OPERATIONS)~~ I found the table in [FAA atc manual](http://www.faa.gov/documentlibrary/media/order/atc.pdf), the airplanes maybe its ok, please check for me.

**Comment by erikquinn** [comment]
@MaicomMR Thanks for the help; I was able to fix the rest of the conflicts, and checked/fixed those values for you.

**Pull request merged**
