### PR TITLE
STARs and Minor Misc Fixes

### LINKED ISSUE #485: Standard Terminal Arrival Routes
We've got SIDs, and #464 reworked some things to improve upon the fms, and the next logical step is to add STARs with the same format as the SIDs. Should be pretty quick and easy work.

### PR DESCRIPTION
**Pull request by erikquinn**
Resolves #485.

Enables STARs under the same basic format as SIDs, and fixes a few other items I came across, such as:
- Localizer draw distance not being drawn separately for each end
- Undoes my previous removal of the circular reference between `Aircraft` and `FlightManagmentSystem`, who both have each other as a property (apparently this is not an issue in modern JS, and so I put it back to the way it was, as it is much easier to work with). Verified this does _not_ adversely affect performance.
- Adds various improvements to arrival spawning methods (now three methods available: `cyclic`, `wave` (different than it used to be!), and `surge` (new version of the old "wave", that takes more useful parameters: `frequency`, and `entrail`, where you specify the entrail distance during the heavy part of the push, and the math does the rest to achieve the desired frequency)
- Adds explanations and diagrams of arrival spawning methods
- Adds logic that checks to make sure the fixes referenced in an airport are all actually present in the fix listing (logs warnings)

Also worth noting that aircraft will now spawn at the first point along the STAR if spawning via stars. See `ksfo.json` to see how entries within the `arrivals` section is changed to acommodate spawning along a STAR.

### CODE REVIEW

**Comment by jakobeng1303** [comment]
I suppose the planes won't descend without altitude restrictions, will they?

**Comment by Alpi-no** [comment]
The demo is not working in safari!
It stops loading the airport when the plane rj85 is being loaded. I don't know why. It runs on Chrome tough. 
When trying to start, I figured out, that taxiing wouldn't work. Not taxi, nor wait. I wasn't able to send "taxi" to the plane. When typing taxi runway 28R/L//(0)1R/L the game would put out the message "callsign, no runway RUNWAY xx". At least it did react to the message and I was able to "send" it. And it's pretty laggy! And 5 mins after the start of the game, it crashes! (I played it on max speed though)

**Comment by erikquinn** [comment]
In investigating this^, I did stumble across one thing where issuing `caf` **before** taxiing will cause a false positive readback:
image

---

@jakobeng1303 The Safari issue is actually unrelated to this, as you'll see if you try to go to the normal [zlsa.github.io/atc](http://zlsa.github.io/atc) in Safari. That is related to a known issue, #477, which I updated to include Safari as well.

Taxiing is working fine from what I'm seeing...

> When typing taxi runway 28R

Perhaps this is the issue; are you actually typing `taxi runway 28R`? If so, that would do it, as the correct command would be simply `taxi 28r`.

Ref. the last problem about timewarping, that is also pre-existing and being investigated in issue #483. If you could describe in greater detail with screenshots and/or console messages and/or s screen recording how that is happening, please head over to #483 and put your comments there so we can get it cleaned up.

But as it stands, I don't believe any of the above are related to this PR in particular.

**Comment by Alpi-no** [comment]
@erikquinn You are absolutely right with the taxiing. My bad! 
The problem with the other things is that all of them only occur in your demo, not in the regular game. That's why I thought, it might be helpful!

**Comment by Fechulo** [comment]
This is great! I would like to know exactly how surge and wave work, but apart from that, I say merge it! If/When we decide to have a center control mode, a 'star' command might be useful to have, however we don't need it right now.

**Comment by Alpi-no** [comment]
@Fechulo I think that a star command might be very useful right now because it suits the purpose better than just `route` or `rr`. Another way could be `callsign c(leared) xx (star)`

**Comment by Fechulo** [comment]
@jakobeng1303  I said that it wasn't useful right now, because aircraft enter the airspace already following a star. In the case of Vienna you might be confusing stars with RNAV transitions. regarding the alternative command, I'd  personally stick with [callsign] STAR [name of STAR], since the command [callsign] C [name of STAR] might have conflicts with the 'CLIMB' / 'C' command.

**Comment by Alpi-no** [comment]
@Fechulo that is probably the best one

**Comment by erikquinn** [comment]
Okay, if it seems good to you guys, we can go ahead. :smile: And then I think it'll be time to update the documentation to reflect the changes and tackle the pile of small bugs that have come up lately... (yawn!)

@Fechulo there are some thorough descriptions in the code, see `airport.js` in each of the `zlsa.atc.Arrivalxxxxxxx` definitions. I'll work on getting the other documentation in sync with what's shown there, but there should be enough detail there to outline it. Basically, the old "wave" is now called "surge" (but takes different parameters), and the new "wave" is just like "cyclic", but instead of rate of change of the arrival rate being _constant_, it will oscillate from the highest rate to the lowest rate in a sinusoidal pattern. There are pictures that explain it better in commented-out code.

**Pull request merged**
