### PR TITLE
EDDF V2.0

### PR DESCRIPTION
**Pull request by Alpi-no**
I added in additional transitions like `T63PSA25S` that are the old transitions. The new ones are with changed entry points and in the case of the UNOKO and ROLIS arrivals, also with some that are as close as possible to the the controllable map. 

Has anyone got the time to work on a refined airspace to allow the controller the fully potential of the EDDF_APP position (increase the range in the areas around ROLIS und UNOKO and the flight routes from there into EDDF)

- [x] Transitions 

- [ ] New map

- [ ] Working properly

### CODE REVIEW

**Comment by erikquinn** [comment]
@jakobeng1303 How about [this](https://skyvector.com/?ll=50.21804016530574,8.569335930801108&chart=302&zoom=3&fpl=UNOKO240010%20UNOKO300010%20UNOKO360005%20IBVIL040005%20MANUV056005%20ROLIS248005%20ROLIS308010%205035N00752E%20ROLIS086005%205019N00816E%205031N00922E%205031N00927E%205038N00926E%20KERAX355010%205039N00942E%205035N00942E%20KERAX042010%205026N00950E%205023N00936E%204956N00942E%204945N00931E%204945N00913E%204948N00913E%204950N00902E%204944N00849E%204944N00824E%204946N00752E%204950N00742E%20RAMOB230005%20MANUV246005%20UNOKO180005%20UNOKO240010)?

image

image

Seems kinda goofy though.

**Comment by erikquinn** [comment]
After minor corrections:
image

Note that terrain would have to be redone.

**Comment by Alpi-no** [comment]
Looks absolutely great! We might wanna give it some more space around DF644, if we want to think ahead for 07 arrivals! We could also cut out FUL in the Northeast because it has no point of being on the map!

**Comment by Alpi-no** [comment]
This is starting to look absolutely fantastical! Just one thing, have you tried KERAX25S arrivals because there might not be enough space in our airspace to cope with them (heading south to PSA after  KERAX

**Comment by erikquinn** [comment]
> We might wanna give it some more space around DF644, if we want to think ahead for 07 arrivals!

I was trying to avoid annexing more and more airspace, and took airspace beyond the depicted blue airspace lines only when necessary to build a corridor that reaches the clearance limits of the STARs. We should probably avoid deviating from the depicted airspace for other reasons, unless we are able to somehow find the boundary of the associated outer area for the EDDF approach control facility.

> We could also cut out FUL in the Northeast because it has no point of being on the map!

Might they come down `TIROT T152 KERAX` sometimes though?

> Just one thing, have you tried KERAX25S arrivals because there might not be enough space in our airspace to cope with them (heading south to PSA after KERAX

Looks like they would make it:
image

**Comment by Alpi-no** [comment]
I can understand your point with the blue airspace and with the current wind situation, it shouldn't be a problem! To be fair, I don't know, whether they'll come down via T152 but it is possible, as KERAX is the beginning of the transition and the clearance limit. 

Could you update your version form before with all the new information e have know including the new STARS and have a look at it? :)

**Comment by Alpi-no** [comment]
Have you had the chance to test it? @erikquinn

**Comment by erikquinn** [comment]
Unfortunately not, I've been busy focusing on my training at work, and giving priority to helping/testing/reviewing the ongoing changes to the game itself as opposed to the individual airports. I'll get around to it sometime, but to be honest there are many other things I'm behind on that I'd like to take care of first. Maybe somebody else could be of help? See my `eddf-airspace` for the boundaries.

**Comment by Alpi-no** [comment]
absolutely no problem!

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), and thus, all pull requests are being closed. If you would still like to see this merged into the simulator, please reopen the pull request at the new repo. Thank you!

Closing this PR.

**Comment by Alpi-no** [comment]
Rgr thanks

**Pull request closed without merging**
