### PR TITLE
[ready] Added Budapest Airport and Wizz Air

### PR DESCRIPTION
**Pull request by abelorosz**

### CODE REVIEW

**Comment by abelorosz** [comment]
@erikquinn did you close this because of the v3 update?

**Comment by erikquinn** [comment]
@abelorosz I have no memory of closing this issue.... I definitely didn't mean to; it must have been a mistake! Reopening.

**Comment by erikquinn** [comment]
Oh I think I see what happened. You targeted the `v3` branch, which I deleted. Maybe when that happens github closes any PRs to that branch as well. In any case, thanks for pointing this out!

**Comment by abelorosz** [comment]
Thanks! I'm gonna update it for v3 :)

**Comment by abelorosz** [comment]
@erikquinn I've finished the update :) Airport is ready for use

**Comment by erikquinn** [comment]
@abelorosz We are in the process of getting everything moved over to the new home of the simulator: [https://github.com/openscope/openscope](https://github.com/openscope/openscope). Would you be able to close and reopen this pull request at the new repository? All issues and pulls here will soon be closed, and I want to make sure this one ends up getting merged into the sim. 😄

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), and thus, all pull requests are being closed. If you would still like to see this merged into the simulator, please reopen the pull request at the new repo. Thank you!

Closing this PR.

**Pull request closed without merging**
