### PR TITLE
Refactoring, Navmode & preparations for Waypoints

### PR DESCRIPTION
**Pull request by niklasfi**
In preparation of my enhancement of #22, I've spent a little time with [aircraft.js](https://github.com/zlsa/atc/blob/gh-pages/assets/scripts/aircraft.js). Hope you  like the changes, especially the documentation added in 52760f4.

### CODE REVIEW

**Comment by zlsa** [comment]
Much nicer, thanks a lot and sorry for my sloppy code.

**Comment by Diastro** [comment]
Haven't had the time to investigate but the build is broken.

 Uncaught TypeError: Cannot read property '0' of null at arcraft.js:860

Command issues to repro : plane a direct berks climb 8000

@niklasfi Do you have time to check is your PR is causing this? Else maybe we should revert for now (@zlsa)

**Comment by Diastro** [comment]
Actually when ever you direct a plane to a fix, we get the error. I'll revert for now. @niklasfi I didn't have time to investigate :S, feel free to push again when you've figured out what the issue is!

**Comment by zlsa** [comment]
I'll investigate now.

**Comment by niklasfi** [comment]
@zlsa sorry, I was away from the computer for a couple of hours. I think I've fixed it now. A simple `this.reqeuested.navmode = null` was missing in `cancelFix`. I'll test it for a bit and then reupload,

**Comment by Diastro** [comment]
@niklasfi zlsa has pushed the fixed and your PR was merged. Thanks

**Pull request merged**
