### PR TITLE
New Airport: KPDX (Portland International Airport)

### PR DESCRIPTION
**Pull request by Fechulo**
This is my second take at an American airport, and to be honest, I'm pretty proud of it. This is also the first time I make an airport with a video map! There's some interesting mountains to the east of the airport, but unfortunately, the P80 TRACON is not big enough to see them.
kpdx

### CODE REVIEW

**Comment by erikquinn** [comment]
lookin' good! workin' good! :+1: :+1:

**Comment by erikquinn** [comment]
@Fechulo PS don't throw away the qGIS files, as we may want to come back later and clean up the edges a bit. Overall, very nice work though! It's a fun little airport I think!

**Comment by Fechulo** [comment]
Thanks for the feedback! I was surprised as to how easy it actually was to add the video map. Nowhere near as difficult as terrain! :smile:

**Comment by erikquinn** [comment]
True dat... The terrain is by far the most painful... lol

**Pull request merged**
