### PR TITLE
Update 1990'

### PR DESCRIPTION
**Pull request by MaicomMR**
This contribution aims to add an airport in the 90s, in the future the
data contained herein may be used to expand this experience. data
contained in this contribution:

-AIRPORTS
KLAX 1990 '

-AICRAFTS
DC8-70 (Dc87)
DC9-30 (DC93)
MD-80 (MD80)
BOEING 727-200 (B722)
BOEING 737-200 (B732)
BOEING 747-200 (B742)
Boeing 747SP (B74S)
L1011 TRI STAR (L101)

-AIRLINES
Pan Am (PAA)
Trans World Airlines - TWA (TWA)

### CODE REVIEW

**Comment by tedrek** [comment]
#356 changed the aircraft rate.ascent to rate.climb, could you update this pull accordingly and resolve the conflicts?  Thanks.

**Comment by MaicomMR** [comment]
@tedrek I will do this :smiley: 

[edited] Done, It's ready.

**Comment by tedrek** [comment]
@MaicomMR, thanks for the update.

Note the capitalization of filenames is important, B74S.json and DC87.json needed to be changed to b74s.json and dc87.json to work.  It probably works fine if you test locally under windows but will fail when served from a Linux system.

Again, thanks for all the work :+1:

**Comment by MaicomMR** [comment]
Thank you, you need me to rename the aircraft? if you want you can create a new commit.

**Pull request merged**
