### PR TITLE
Indonesian airports and airlines (WIII and WIMM)

### PR DESCRIPTION
**Pull request by ghariman**
Tested on: ghariman.github.io/atctest/

### CODE REVIEW

**Comment by ghariman** [comment]
Please help to squash when merging

**Comment by erikquinn** [comment]
@ghariman is it just this commit that you want to keep? 97a47fd

**Comment by ghariman** [comment]
Hi Erik,

Yes that is the one.

How do I request a pull next time of only the new commits and not the old ones?

Thanks.

**Comment by erikquinn** [comment]
@ghariman It has to do with the base revision from which you start your work. Basically, the only way to do it is by maintaining 2+ branches: one that is only updated to stay in sync with `zlsa/gh-pages`, and then you create branches off of that branch when you want to make changes you eventually plan to do a pull request with.

The reason this PR shows so many commits is because of the revision of `zlsa/gh-pages` it is "based from". Your `gh-pages` branch is currently "based on" commit 2c142125fe799915167d666f812ee52ac75412ff, from back in early March. All the changes you have made are then piled up on that one. Other than changes you've made, your `gh-pages` branch does not have any changes that have been merged here after March 7th. So the problem is that, inevitably, whatever you change will probably have been changed by someone else between March and today, and the reviewer has to figure out which change to keep, or how to combine them correctly. To fix it, you will need to get your branch in sync with `zlsa/gh-pages`, and then that will be the new "base", and any commits you add will be the only ones that will show up in a pull request.

It looks a bit like this:

```
    March 7th                                     May 9
    |                                             |
    v                     (zlsa/gh-pages)         v
A-B-C-D-E-F-G-H-I-J-K-L-M-N-O-P-Q-R-S-T-U-V-W-X-Y-Z
    |
   fork                                                              May 9
    |                                                                |
    v                   (ghariman/gh-pages)                          v
    C-a-b-d-e-f-g-h-i-j-k-l-m-n-o-p-q-r-s-t-u-v-w-x-y-z-aa-ab-ac-ad-ae
    [- - - - - - - - - - - - - - - old - - - - - - - - - - - - - -]  ^
                                                                     |
                                                                     commit indonesian stuff
```

And it should look more like this:

```

    March 7th                                     May 9
    |                                             |
    v                     (zlsa/gh-pages)         v
A-B-C-D-E-F-G-H-I-J-K-L-M-N-O-P-Q-R-S-T-U-V-W-X-Y-Z
                                                  |
           <--- git pull zlsa/gh-pages <---       |
    +---------------------------------------------+
    |
    v
    Z     (ghariman/clean)
    |
git branch
    |
    v
    Z-a-b-c-d-e-f-g-h-i-j-k-l-m-n-o     (ghariman/project1)
      [commits in the pull request]
```

And as long as you set up `ghariman/clean` correctly, all you have to do when you start a new project is, on the `clean` branch, in the git shell, type `git pull zlsa/gh-pages` to update `clean`, and then branch off to do your work, like `git checkout -b project1`. Add your commits, and make the pull request, and then only the changes you've made in the `project1` branch will be included. 

If you want to hop on the [zlsa gitter chat room](https://gitter.im/zlsa/atc) (it's easy, just click 'sign in with github'), I'd be happy to walk you through any part of it.

**Comment by erikquinn** [comment]
This has been merged via commit ba43181e4b14ab911cc6b3ddbccf081c717b9888. Closing.

**Pull request closed without merging**
