### PR TITLE
SBGL and SBGR update

### PR DESCRIPTION
**Pull request by MaicomMR**
SBGL and SBGR airports converted to real coordinate systems, runways and waypoints(a lot of real waypoints added)

### CODE REVIEW

**Comment by MaicomMR** [comment]
Have a little error here, the "Merge pull request #2 from zlsa/gh-pages …" is not my work, how i can delete this item?

**Comment by glangford** [comment]
Following this link:
http://stackoverflow.com/questions/927358/how-do-you-undo-the-last-commit

I think what you want to do in your SBGR_improvment branch:

`git reset --hard HEAD~1`

Then push. Any better ideas out there?

**Comment by MaicomMR** [comment]
I actually wanted to send only the "SBGL and SBGR update", but was also the "#2", which was an import that I did for my local version, is I enable a way of my fork upgrade to the same version of zlsa automatically ?

Sorry for asking questions so noobs.

**Comment by glangford** [comment]
@MaicomMR - to upgrade your fork to the same version as zlsa, here is a link to some documentation below. zlsa's repository uses a "gh-pages" branch instead of master, so what I do is:

```
git checkout gh-pages
git fetch upstream
git merge upstream/gh-pages
git push origin gh-pages
```

https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/

Does that help?

**Comment by glangford** [comment]
@MaicomMR - Working with Remotes / Trabalhando com Remotos (em português!)

https://git-scm.com/book/pt-br/v1/Git-Essencial-Trabalhando-com-Remotos

**Comment by MaicomMR** [comment]
Hey @glangford very thanks my friend, you is a big leader, you search for portuguese articles to help me :)
I dont know use commands on github, i'm using the desktop version(windows), I solve this deleting(close) the old pull request. Now I create a new branch and add my contribution, I put on the pull request list. (SBGL and SBGR update #192)

Really very thanks for your help!

**Pull request closed without merging**
