### PR TITLE
[New airport] EPWA - Warsaw Chopin Airport

### PR DESCRIPTION
**Pull request by MikePapaSierra**
Hi all,

As I mentioned in [issue](https://github.com/zlsa/atc/issues/3), I was working over first of Polish airports, EPWA - Warsaw Chopin Airport. Now I can proudly say that new airport is ready to be merge in to the main project. Of course there are some issues related to specification of this particular TMA that need to be solved but I will be working on that issues further. Short description of EPWA airport was placed in documentation section. Any feedback is welcome!

### CODE REVIEW

**Comment by MikePapaSierra** [comment]
Hi all,

I added restricted zones to EPWA TMA and improved traffic flow.

**Comment by MikePapaSierra** [comment]
Hi all,

I updated my repository to current version to make merge easiest.

**Comment by erikquinn** [comment]
@kamikazestar We are in the process of getting everything moved over to the new home of the simulator: [https://github.com/openscope/openscope](https://github.com/openscope/openscope). Would you be able to close and reopen this pull request at the new repository? All issues and pulls here will soon be closed, and I want to make sure this one ends up getting merged into the sim. 😄

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), and thus, all pull requests are being closed. If you would still like to see this merged into the simulator, please reopen the pull request at the new repo. Thank you!

Closing this PR.

**Pull request closed without merging**
