### PR TITLE
Warnings are penalized [wip]

### PR DESCRIPTION
**Pull request by culebron**
Right now warnings (close approaches) are not penalized. I added this scoring, but right now it also penalizes parallel approaches in KSFO (#261). This has to be fixed.

You may try the new behaviour at http://culebron.github.io/atc/

### CODE REVIEW

**Comment by Maverick283** [comment]
This only means that the "red circles" are penalized, but the white ones aren't, right?

Code looks like you already fixed the parallel approach issue?

**Comment by culebron** [comment]
No, not fixed yet.

**Comment by Maverick283** [comment]
Hm, reading this wrong then.

Wouldn't a simple condition checking for the ILS locking status of an aircraft do the trick? As in:

If (!isLockedOnILS) {
    //Do the whole speration thing
} else {
   //aircraft is immune to any separation calculations, maybe needs an additional variable
}

**Comment by culebron** [comment]
This is too simple, because this will permit situations like in the picture: one or both planes come from the wrong side and get ILS locked in the corridor triangle, still on the wrong side, without triggering a penalty.

selection_030

I think we need to check and make an exception (not trigger a warning) if both planes are landing on a parallel rwy and have separation >300 ft. But this still permits situation like in the picture. I think we need to add one more condition: planes should be on different sides of the glide paths (or middle of the 2 glide paths).

**Comment by Maverick283** [comment]
Okay, say we have aircraft 1 (a1) and aircraft 2 (a2). a1 is already on the glidepath, e.g. for rwy 09L. 
The rule is that a aircraft may only fly closer to another aircraft when it has it insight, only then it may start the parallel approach. For simulation, we could adopt this and say that the aircraft may only close in from the side it will fly its approach at. 

So with a1 being on the approach, a2 may come closer to a1, but may not come any closer then the distance between the two runways (here also the approaches). 

This would require to be able to tell how far a aircraft is to the right/left of another aircraft. Then you would have to know the distance and whether one approach is to the right or left of another. 

This is the solution with the best efficiency that I can come up with right now....

**Comment by tedrek** [comment]
#294 has a significant re-factor to the whole notice/warning system but doesn't include the warnings being penalized.

If the reduced lateral separation of 600 feet (or so) is only in place while the aircraft are within say 75 feet of the centerline, then the crossing case will be correctly penalized if there is not sufficient vertical separation at the time.

The only other piece I think is missing is setting flags on the SFO runways in particular to allow such a separation.  Pulling the same stunt at LAX should be a major no-go.

**Comment by erikquinn** [comment]
All issues discussed here were addressed and resolved in a recent merge (#426).

**Pull request closed without merging**
