### PR TITLE
New Airport: SAWH (Ushuaia Airport)

### PR DESCRIPTION
**Pull request by Fechulo**
Ushuaia Airport, officially "Aeropuerto Internacional Malvinas Argentinas" (A very controversial name as it reflects Argentina's claims of sovereignty over the Falkland Islands) is a small airport at the southern tip of Argentina in Ushuaia, the southernmost city in the world. I made this airport mainly because I wanted to play around with terrain (I think it looks pretty good, although there are some errors north of the airport, where there's two overlapping areas with an elevation of 1000ft).

This PR also includes changes to LAN and TAM, since the 2 airlines have merged into one airline called LATAM. 

When #561 is merged, d8d0de9 and c9df00e will become unnecessary.

### CODE REVIEW

**Comment by tedrek** [comment]
@Fechulo, I am getting a parse error on sawh.json line 50.  Could you please fix so it passes JSON validation?

If possible also rebase/merge to resolve the merge conflicts

**Comment by Fechulo** [comment]
@tedrek I'm currently away and I'm not able to do anything with my phone. I'll be home this evening, so I'll do it then. (~2300z)

**Comment by tedrek** [comment]
Heh, and here I was going to be happy if you got to it within a couple of weeks :wink:

**Comment by Fechulo** [comment]
Haha, I was actually too tired to do it yesterday, so I'll do it today. I might close this PR and open a new one with the fixes.

**Pull request closed without merging**
