### PR TITLE
Update TutorialView.js

### PR DESCRIPTION
**Pull request by panther2**
to add the required 'space' between the 'fh' command and it's argument.

### CODE REVIEW

**Comment by n8rzz** [comment]
@erikquinn This change may be better suited in my fork?  We are trying to keep all the JS updates in one place so they can all be merged as part of a numbered release.

**Comment by panther2** [comment]
So what are the rules to either contribute to this repo or to yours, @n8rzz ?

I mean people who want to learn from the tutorial right now will get wrong information from there...

Also I read from 
https://github.com/zlsa/atc/blob/gh-pages/README.md :

> Contributing 
> Just create a pull request and I'll get to it. Thanks for helping!

Any background information about how this is organized is well appreciated. Thanks.

**Comment by n8rzz** [comment]
That is why I defer to Erik here.  This is a super minor change, and would be easy to merge in here.  My point is just that we are doing most, if not all, of the JS work within my fork so we can avoid many small changes to the main repo.

That section of the readme is targeted more towards airport contributors.  Up until recently, most contributions on this project were in the form of Airports or Aircraft changes.

If you would like to contribute to the JS, we'd love to have you!  I do need to put together a JS contributor doc to help here, but in the mean time:
- Clone my repo.  you will be contributing via feature branches and making commits directly to my fork 
- read the readme in the tools directory and the gitflow readme (this also needs updating)
- Take a look at the issues in my fork and see if there is anything there you would like to help out on.
- Join our [slack channel](https://zlsa-atc.slack.com/)
- Ask questions!

and we can take it from there.  I have some very specific (undocumented ☹️) procedures that I like contributors to follow, so please reach out if you are planning on contributing.

**Comment by erikquinn** [comment]
I realize it is confusing and somewhat disorganized/counterintuitive/etc. It really doesn't matter either way, there will be some sort of reorganization in the near future that will make the problem moot. But for now, you can just leave it here, and I'll take care of getting the fork up to date with the changes to `zlsa/gh-pages`. In general though (for the next little bit), it is convenient if js changes can take place on the `n8rzz` fork, so that they are all merged in at once. That is the current thinking anyway. :)

**Comment by panther2** [comment]
Thanks for the background information @n8rzz and @erikquinn . Very interesting.

Some days ago I had already successfully tested to run the sim locally, using node.js .

In the next days I will take a closer look at both of the repos to find out if and how I can possibly further contribute.

**Comment by panther2** [comment]
Additional question: How do you keep track of the issues opened at zlsa/atc and/or n8rzz/atc ?
Do you regularly "scan" each repo and open - after sort of approval - a respective issue at the other repo, too?

**Comment by erikquinn** [comment]
For visibility, if it's an issue a user is likely to encounter, I put it up here so they can see we know about it, and they can add comments, etc. And then a parallel issue is created in the fork, referencing the original one here at the main repo. The issue is resolved on the fork, packaged up into a single monthly release, which is done via a pull request merged back into the main repo, with links to all the issues it resolved.

If it is an issue that users wouldn't care about, such as code reorganization, I just put it in the `n8rzz/atc` fork directly.

**Comment by n8rzz** [comment]
We do maintain the a changelog in my fork as well, which contains links to all the changes contained within a release: https://github.com/zlsa/atc/blob/gh-pages/CHANGELOG.md

**Comment by panther2** [comment]
Understand, thanks for the insight.

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), and thus, all pull requests are being closed. If you would still like to see this merged into the simulator, please reopen the pull request at the new repo. Thank you!

Closing this PR.

**Pull request closed without merging**
