### PR TITLE
EDDM with magnetic_north and SIDs

### PR DESCRIPTION
**Pull request by harp71**

### CODE REVIEW

**Comment by harp71** [comment]
Hi, sorry for mess again, i obviously still don´t get the commit, pull request thingy. relevant here is only   EDDM new with magnetic_north and SIDs.

**Comment by harp71** [comment]
i still don´t get this github crap, sorry. maybe someone can teach me how to do things right.

**Comment by avdg** [comment]
Troubles rebasing? Not sure where to chat...

**Comment by tedrek** [comment]
@harp71, I am available on gitter [Join the chat at https://gitter.im/zlsa/atc](https://gitter.im/zlsa/atc?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

I would be happy to help you get this PR sorted out.

**Comment by harp71** [comment]
Thanks a lot, i joined the chat and described my problem there in detail.

**Pull request closed without merging**
