### PR TITLE
update KSFO (tested on http://ghariman.github.io/atc/)

### PR DESCRIPTION
**Pull request by ghariman**
Difference from curent/original:
- Updated with complex SID from ZLSA
- added/adjusted more airlines to the correct arrival points
- removed EUGEN1 and swapped with PORTE7
- added Pacific arrival point into PIRAT->OSI

Tested on: http://ghariman.github.io/atc/
(choose KSFO airport)

### CODE REVIEW

**Comment by ghariman** [comment]
I updated KSFO (with new complex SID) with the following changes:
- added/adjusted more airlines to the correct arrival points
- removed EUGEN1 and swapped with PORTE7 (based on traffic observation on flightradar24)
- added Pacific arrival point into PIRAT->OSI (based on traffic observation on flightradar24)

Tested on: http://ghariman.github.io/atc/
(choose KSFO airport)

**Comment by Fechulo** [comment]
It looks good, I just have two questions:  
1. Why did you delete B747S, DC87 and L101?  
2. Is it necessary to keep the original KSFO file?

**Comment by ghariman** [comment]
Hi,
1) there is a non-capital letter version of those it seems. For some reason when I copied ZLSA's files there was capital-letter for those 3 so I deleted them.2) ksfooriginal.json was just my own local backup copy. I will erase it.

```
  From: Fechulo <notifications@github.com>
```

 To: zlsa/atc atc@noreply.github.com 
Cc: ghariman ghariman@yahoo.com
 Sent: Wednesday, March 16, 2016 4:25 PM
 Subject: Re: [atc] update KSFO (tested on http://ghariman.github.io/atc/) (#411)

It looks good, I just have two questions:
1. Why did you delete B747S, DC87 and L101?
2. Is it necessary to keep the original KSFO file?—

**Comment by ghariman** [comment]
I also made modification to KLAX (the non-90's one):
- added/adjusted more airlines to the correct arrival points
- removed SNG06 and swapped with LAXX8.MZB (based on traffic observation on flightradar24).
- added VTU6 compex sid with transitions to GMN (north inland) and RZS (north offshore)
- added Pacific arrival point from VTU into SADDE6 arrival
- refined the LOOP8 sid by adding extra waypoints so that planes do make a correct left counter clockwise loop

Tested on: http://ghariman.github.io/atc/
(choose KLAX airport)

image

**Comment by erikquinn** [comment]
@ghariman I concur about the removing of `B74S.json`, `L101.json`, and `DC87.json`. They were added by mistake I believe, and all the necessary information is contained in the duplicate files with lowercase filenames, so you are right in simply removing them.

As for the other KSFO changes, tested them, loved them. Good work. One bit of feedback though-- there are a _lot_ of commits here. I won't speak for Jon, but if it were my repo, I wouldn't want them cluttering up the commit history, and would probably ask you to "squash" them (removing intermediate commits), so each commit represents a finished functional change, and not a series of minor edits. Squashing can be done in the git shell with a `git rebase -i` and changing "pick" to "s" / "squash" to remove all the extra commits. This is a somewhat complex git operation though. Easiest resolution would probably be to at least move to the [github desktop client](https://desktop.github.com/), which is just about as user-friendly, but gives you the power to decide when you want to "save" progress with a commit. This also makes it easy to work with branches, which are very helpful in separating different tasks you're working on. I'm happy to help you get it set up if you need.

And again, this is all just a suggestion, from one contributor to another. More than anything, I'm glad to see another new face working to improve the sim! :smiley:

**Comment by ghariman** [comment]
Yes I noticed that I created a lot of commits and it shows up.

The reason being, as you know, I am using the github website as my test-bench as I do not have a local server set up. Thus every time I make a change I commit and sync and test to make sure I do not have a syntax error or if I want to tweak/refine some changes I do it bit by bit.
Let me try the git shell command to clean up the commit history as you suggested.
Also I should learn more about Git and how branches/forks work. I know that it is supposed to help with revision control and how many programmers can work and collaborate on one project together more optimally.

As you may have noticed I also worked on KLAX in addition to KSFO but I did all of the work in the same "gh-pages" branch which is the main (and only one) I have.
I may work on KSAN next.

May longer plan is to be able to start a new airport all together (thinking about Singapore Changi WSSS). But that is still far away. I could not even make a new airline to work properly (I tried to make Virgin America vrd.json file and JetBlue jbu.json file but when I included them in KSFO the KSFO was not able to run so I need to research more - the airport just got stuck).
So still a lot of learning to be done.

**Comment by ghariman** [comment]
Yes I noticed that I created a lot of commits and it shows up.The reason being, as you know, I am using the github website as my test-bench as I do not have a local server set up. Thus every time I make a change I commit and sync and test to make sure I do not have a syntax error or if I want to tweak/refine some changes I do it bit by bit.Let me try the git shell command to clean up the commit history as you suggested.Also I should learn more about Git and how branches/forks work. I know that it is supposed to help with revision control and how many programmers can work and collaborate on one project together more optimally. As you may have noticed I also worked on KLAX in addition to KSFO but I did all of the work in the same "gh-pages" branch which is the main (and only one) I have.I may work on KSAN next.May longer plan is to be able to start a new airport all together (thinking about Singapore Changi WSSS). But that is still far away. I could not even make a new airline to work properly (I tried to make Virgin America vrd.json file and JetBlue jbu.json file but when I included them in KSFO the KSFO was not able to run so I need to research more - the airport just got stuck).So still a lot of learning to be done.

**Comment by erikquinn** [comment]
@ghariman Hmmm, sounds like perhaps you didn't tell the game to load the airline? There's a long list of them somewhere, I think maybe in `game.js` or something. There's like a billion lines of just `airline_load("ual.json")` or similar; add the new airlines to that, and assuming the syntax in the actual json is correct, they should load, and if included in the airport json, they should appear.

**Comment by ghariman** [comment]
Hi Erik,
I have never ventured into the actual js files before. Only touched the json files.And it is airlines.js by the way, so I will need to modify this to include the new ones.I'll try to look into it.It will be more fun to include more airlines for KSFO especially Virgin America (hub is KSFO) and many more.
Thank you for the info.

```
  From: Erik Quinn <notifications@github.com>
```

 To: zlsa/atc atc@noreply.github.com 
Cc: ghariman ghariman@yahoo.com
 Sent: Friday, March 18, 2016 11:21 AM
 Subject: Re: [atc] update KSFO (tested on http://ghariman.github.io/atc/) (#411)

@ghariman Hmmm, sounds like perhaps you didn't tell the game to load the airline? There's a long list of them somewhere, I think maybe in game.js or something. There's like a billion lines of just airline_load("ual.json") or similar; add the new airlines to that, and assuming the syntax in the actual json is correct, they should load, and if included in the airport json, they should appear. —

**Comment by erikquinn** [comment]
@ghariman I was able to squash these for you, and the changes are now in a single commit (7e86041), which will now be merged.

**Comment by erikquinn** [comment]
This has been merged via affdca0. Closing.

**Comment by ghariman** [comment]
Erik,
Thank you so much.
Next time I will try to be more clean when I make some suggested changes/pull requests. I need to learn more about forks, merge, etc in github so that I can do my experiments not in the main version.

**Comment by erikquinn** [comment]
@ghariman no problem! I'm loving using the PORTE7  already, it always drove me up a wall how OFFSH9 and EUGEN would converge around ZUPAX... :laughing: 

Keep the good stuff coming! :smile:

**Comment by ghariman** [comment]
Erik,
I have a question. I currently have the below repository:github.com/ghariman/atc/github.com/ghariman/atctest/ where I want to use to test my updates/changes etc.
When I go to ghariman.github.io/atc/index.html it launches the github.com/ghariman/atc/index.html and of course the ATC game starts.
But when I go to ghariman/github.io/atctest/index.html I get a 404 page not found. Do you know why?
Thanks.

**Pull request closed without merging**
