### PR TITLE
Add LKPR airport

### PR DESCRIPTION
**Pull request by luznicky**
So far is done:
- airport layout and TMA related things
  - all SIDs
  - STARs for RWY 06
  - 60 movements/hour (30arr/30dep)

To be done:
- consider adding STARs unless it makes screen more messy.
- have SIDs and STARs for all possible rwy configurations or have less fixes
- make ARR/DEP airlines closer to reality
- TMA shape (little problematic as it's defined using circular sectors)

Sources:
- http://www.vacc-cz.org/en/component/phocadownload/category/4-lkpr-dw?download=110:lkpr-charts
- http://www.ivao.cz/downloads/IFRTOUR/LKPR.pdf

### CODE REVIEW

**Comment by luznicky** [comment]
So far is done:
 - airport layout and TMA related things
  - all SIDs
  - STARs for RWY 06
  - 60 movements/hour (30arr/30dep)

To be done:
 - consider adding STARs unless it makes screen more messy.
 - have SIDs and STARs for all possible rwy configurations or have less fixes
 - make ARR/DEP airlines closer to reality

Sources:
 - http://www.vacc-cz.org/en/component/phocadownload/category/4-lkpr-dw?download=110:lkpr-charts
 - http://www.ivao.cz/downloads/IFRTOUR/LKPR.pdf

**Comment by Fechulo** [comment]
Hi @luznicky, What you've done so far is looking really good! if you need help with the TMA, I can teach you how to do it. When testing the airport, I found that the game crashes when aircraft following the GOLOP arrival fly to KUVIX. This is because the waypoint KUVIX is not defined in the fixes, but it's still used in the GOLOP arrival.

**Comment by luznicky** [comment]
Hi,
i decided to finish the STARs. It's bit messy, but I decided to take a look at possibility to draw only FIXes relevant for RWYs in use.
I'll appreciate help with TMA shape. Then I'll do some polishing and I think that it'll make LKPR nice enough to play.

**Comment by Fechulo** [comment]
No problem! [Here](http://lis.rlp.cz/ais_data/aip/data/valid/e2-1.pdf) are the coordinates for the Praha TMA (pages 24-28). For the circular areas, you can use [GPSVisualizer](http://www.gpsvisualizer.com/calculators#coordinates) to find the coordinates of a circle around a certain point (In this case, the OKL DME). I recommend drawing all the points for the TMA, as if they were normal fixes. Then you can manually select the ones you need and use their coordinates to form the overall TMA. I know this can be a bit confusing, so if you need more help, let me know!

**Comment by Fechulo** [comment]
This just occurred to me. Are you testing your changes locally? If you're not, it would be impossible to get the TMA form the method I described. If you want to test your changes, you can follow the steps on the [wiki](https://github.com/zlsa/atc/wiki/***NEW-CONTRIBUTORS-HELP***).

**Comment by luznicky** [comment]
I have an Apache on my desktop, so I am using it. GPSVisualizer works fine. I got few points from the generated list by hand. But for next TMA sed script or some macro for reformatting is a must. I just committed it because I couldn't get the missing circles back. (OK, removing whole airspace part works, but that's not what I want. )

**Comment by Fechulo** [comment]
I personally recommend [Sublime Text](https://www.sublimetext.com/). It's a code editor, but most importantly, it allows you to edit multiple lines at once, which makes re-formatting very easy.

**Comment by erikquinn** [comment]
is this ready for review?

**Comment by luznicky** [comment]
Hi,
I'll finish it as soon as I return from vacation. Prob.  this weekend. I thought that I would be faster. Sorry for delay.

**Comment by luznicky** [comment]
Hi @erikquinn,
lets call it ready for review now.

**Comment by erikquinn** [comment]
Everything seems to be in order! Nicely done :smile:

**Pull request merged**
