### PR TITLE
SBGL and SBGR update

### PR DESCRIPTION
**Pull request by MaicomMR**
SBGL and SBGR converted to real coordinate system, added real waypoints
and improved with the real distances between they.

### CODE REVIEW

**Comment by culebron** [comment]
Is this actually merged? I see SBGR was merged (new compaines appeared), but SBGL seems not, I don't see the new fixes.

**Comment by glangford** [comment]
> Is this actually merged? I see SBGR was merged (new compaines appeared), but SBGL seems not, I don't see the new fixes.

The page for this pull request says "This branch has conflicts that must be resolved."

Can the pull request be resubmitted or updated with the missing changes?

**Comment by culebron** [comment]
The branch that is in request can pull from the target branch, and this way it will work. I see SBGL actually has some changes in airlines but not in fixes. I created another branch, called "brasil", will check and try merging with the main one.

**Comment by MaicomMR** [comment]
@glangford what I need to do to be able to merged?

**Pull request merged**
