### PR TITLE
Update LOWW

### PR DESCRIPTION
**Pull request by Alpi-no**
Demo: http://lachsschinken124.github.io/atc/

### CODE REVIEW

**Comment by erikquinn** [comment]
@jakobeng1303 @lachsschinken124 Is the work complete on this, or do you need some more time to put a few more changes in before somebody starts to review it?

**Comment by maebruck** [comment]
@erikquinn I think it can be regarded as finished as arrivals, departures and routes are done & optimised; terrain is still pending though due to #613

**Comment by Fechulo** [comment]
@lachsschinken124 the elevation of LOWW is 183m, so there shouldn't be any problems with adding terrain.

**Comment by maebruck** [comment]
@Fechulo: @jakobeng1303 tried it out, but planes still crashed into the terrain whilst climbing

**Comment by Alpi-no** [comment]
@Fechulo I struggled twice to create terrain and both times, I have to admit, I failed (despite the helpful video), so basically this airport is finished except for terrain but that won't make a big difference anyway, because there aren't any hills impacting the sight.

**Comment by Fechulo** [comment]
If you want, I'm willing to add terrain. There's some pretty interesting terrain to the southwest:
sw

**Comment by Alpi-no** [comment]
[pointselev.txt](https://github.com/zlsa/atc/files/367296/pointselev.txt)
It'd be great! I don't think any of the other files would help as I suspect an error somewhere in them. This however should be fine! 
https://www.dropbox.com/s/jj8b1wnr3njg363/LOWWcontour.qgs?dl=0 this is the nearly finished file

**Comment by Fechulo** [comment]
Thanks! Although I think I'll just start from zero.

**Comment by Alpi-no** [comment]
No problem!

**Comment by Fechulo** [comment]
@jakobeng1303 @lachsschinken124 Done!
loww
When this is merged I'll open a PR to add the terrain, or alternatively I could send you the .geojson file

**Comment by Alpi-no** [comment]
You could add it to mine and lachschinkens own copy (https://github.com/lachsschinken124/atc) and it might vine show up in this list (?) 
Thank you!!! We really appreciate your work!

**Comment by Fechulo** [comment]
No problem! I don't think that will work, but you can download the file [here](https://drive.google.com/open?id=0B1Hl6YN-1HP2VnNvYkh2eFlGT2s).

**Comment by maebruck** [comment]
@Fechulo Thanks for your work!

**Comment by erikquinn** [comment]
I've been trying for a while now, but there are some _crazy_ complicated merge conflicts that I can't seem to resolve... I'm not sure why, but it seems like as I resolve each one, it recurs at the very next commit, and everything conflicts with everything, and doing them one by one for a hundred-some commits would take days.

I'm not sure (maybe somebody with more experience with git can confirm/deny), but my theory is that it has to do with commits like the following:  

58e9a89, e7fe4c0, dc5df35, f792e4c, 9237be6, 4916f07, 3395479, 3e8e4f8, 74b5d7e, 41c5650, 2c0041c, 7e8338e  

Perhaps the conflicts are because somebody makes a change to a file, and then _merges_ the latest version of the game instead of _rebasing_ onto it, and then it looks like the changes are being done, undone, and then redone? I don't know... it's just proving very hard to get these changes merged into the main repo.

**Comment by Alpi-no** [comment]
It might help to copy and replace the code of LOWW here, with what we have done. What do you think?

**Comment by erikquinn** [comment]
@jakobeng1303 Right, that's one of the things I tried... the trouble is that this branch is based on a rather old version of the sim. So if I just copy your files and replace the ones we currently have, it effectively undoes all of the changes that have been merged since you started work on this branch. Instead, the proper way for me to fix this in git is by using the `git rebase` command, which will attempt to see what you changed relative to your old version, and apply those changes to the _current_ version. When the changes made in `zlsa/gh-pages` conflict with changes made in your branch, it prompts me to choose and/or change which code to keep. For some reason though, when I go through this process in this case, git is getting confused and giving me tens and tens of lines of code to decide between, and repeats for each one of the hundred-some commits.

There HAS to be some way to do this, but I haven't been working with git long enough to know how to fix it. I can do some more research, but so far all research on how to resolve this has been unsuccessful. I promise I'm trying, I just can't seem to get it sorted out! :frowning:

**Comment by Alpi-no** [comment]
well, what if I would just copy the LOWW code and replace it with the existing one here. I don't recall any changes that were made in the airport file. So basically I would create LOWW V2 sort of and delete V1. This way this branch should have the updated version as well and I would just fork it again. Does that make sense? :D

**Comment by erikquinn** [comment]
@jakobeng1303 @lachsschinken124 I actually think I've got it fixed up... Could you take a few minutes to verify that everything you changed is still working properly at the link below? I think it should be okay, but it's possible some things got messed up in the process.

### Demo: [erikquinn.github.io/atc/b/pr608-fixed](http://erikquinn.github.io/atc/b/pr608-fixed)

**Comment by Alpi-no** [comment]
@erikquinn In my opinion, everything worked but I want to wait for @lachsschinken124 to confirm it.

**Comment by maebruck** [comment]
@jakobeng1303 @erikquinn The website is running w/o any flaws and the code does also look ok, no bugs seem to come up, thank you @erikquinn for fixing up those problems

**Comment by Alpi-no** [comment]
@erikquinn I have to reapeat @lachsschinken124 : thanks a lot!!!

**Comment by erikquinn** [comment]
@jakobeng1303 @lachsschinken124 Okay, great! And my pleasure, I'm glad to see all the new improvements to LOWW! :smile:

I'm still not sure why it ended up being so complicated, but my theory is still that it's related to the `"Merge remote-tracking branch 'zlsa/gh-pages' into gh-pages"` commits. Going forward, even if your work is based on a very old version of the game, either leave it as it is (perfectly fine), or use `git rebase` in the git shell onto the upstream's head (not necessary; for overachievers). Either way, it should then be pretty straightforward for the reviewer to get it merged in. So if you can, just please avoid doing that on any branch you intend to do a pull request with.

I'll get this merged in the next few minutes. Great work guys!

**Comment by erikquinn** [comment]
Merged via 8b271c8! Closing.

**Pull request closed without merging**
