### PR TITLE
[ready & complete] GCRR Lanzarote

### PR DESCRIPTION
**Pull request by willfrd**
Located in the island of Lanzarote it recieves over 6 million passengers per year. This the first airport I´ve created it together with 3 airlines. The airlines are fine but the airport needs change because for some reason it dosen´t load, so any sugestions to fix it are greatly appreciated :-)
Testing:
https://willfrd.github.io/atc/

### CODE REVIEW

**Comment by eliuuk** [comment]
Nice airport! I'll have a look for you real quickly, and see if I can help.

**Comment by willfrd** [comment]
Thanks very much :)

**Comment by eliuuk** [comment]
Found the issue for you, you're missing a few fixes. Here's the output directly from Google Chrome:

> [ WARN ] GCRR uses the following fixes which are not listed in airport.fixes: 52LTE GINAS NIRPO PEPOM

**Comment by willfrd** [comment]
Thanks, I´ll fix it. How did you run it in Google Chrome for errors (I´m new in this), thanks.

**Comment by eliuuk** [comment]
In Google Chrome, press F12 to see the error log.

**Comment by willfrd** [comment]
Ohhh, :D thanks I will use that in the future. Thanks for your help.

**Comment by eliuuk** [comment]
My pleasure! :+1:

**Comment by willfrd** [comment]
After testing it for some time it doesn´t work in Google Chrome but it does in Mozilla and Internet Explorer but the simulation crashes after a few minutes and an error that I don´t know how to fix : "call to vsub() failed. v1:-72.04880587024421,-15.075358945140243 | v2:undefined | Err:TypeError: v2 is undefined" I will keep trying to find where its coming from.

**Comment by erikquinn** [comment]
@willfrd double check the SIDs and STARs. If I remember correctly, historically this issue has often been caused by a small syntax mistake in there, and goes away once it is found and fixed.

**Comment by willfrd** [comment]
Together with the Iast update I created an extra 5 airlines (Vueling, transavia, enter air, travel service and germania) that also fly to lanzarote and added them to the code line. In addition to this I deleted the  Bamku departure because it was unsuitable. My apologies for the excesive commits.

**Comment by willfrd** [comment]
It still crashes after some time so still looking for errors.

**Comment by eliuuk** [comment]
I had this issue with Luton (#592), and it was an issue with a STAR, so what I did was just go through all the STARs one by one and remove those that were incompatible.

**Comment by willfrd** [comment]
Does anyone know what is the way for me to open a link so you guys can test the airport?

**Comment by Conejero-Dev** [comment]
hello willfrd, well done. I'm from Lanzarote and I wanna test your creation, please share with us :)

**Comment by willfrd** [comment]
Nice!!, I´m from Lanzarote and live in Lanzarote, it would be a pleasure for me to leave you try it but I´m new in github and I don´t really know how to publish a link so you can try it. If you or someone  knew how to do this, it would be greatly appreciated if you published a comment in this pull request with the steps, anyways I´m working on how to do it, until then ¡Un saludo! :-)

**Comment by Conejero-Dev** [comment]
Great! To be honest I have no idea about how to share it, if someone can help us... 

Un saludo muchacho!

**Comment by Fechulo** [comment]
The [wiki](https://github.com/zlsa/atc/wiki/***NEW-CONTRIBUTORS-HELP***) contains a lot of info on how you can test your changes. If you want other people to be able to take a look at your additions, [this website](https://pages.github.com/) might be helpful.

**Comment by willfrd** [comment]
Thanks for that Fechulo! Will look into that.

**Comment by willfrd** [comment]
Finally!! After all the afternoon bannging my head against the keyboard I have managed to publish it!!
To test:
https://willfrd.github.io/atc/

**Comment by Fechulo** [comment]
@willfrd It looks really good!! Is there any particular reason for the lack of range rings; these can be very helpful, especially to new players. That said, kudos to you for adding terrain!

**Comment by willfrd** [comment]
Yes it took me some time but I managed to to the terrain. Thanks for the suggestion will look into the rings, and no there is no particular reason, in fact can you tell me why it isn´t loading the rings and/or how to load them (although in my opinion they should be loading). Thanks :D

**Comment by Fechulo** [comment]
@willfrd they are loading, but you set them to be 800nm apart, which means that the first one is 800nm away form the ariport, so you can't see it. You can easily solve it by changing line 14 into 5nm instead of 800nm

**Comment by willfrd** [comment]
ohhh xD thanks for that!

**Comment by Conejero-Dev** [comment]
Aaaaaawesome! Ty mate! <3

**Comment by willfrd** [comment]
NP mate I´m glad someone enjoys it. :) Me alegro de que te guste!, cualquier sugerencia ponla que se agradece (y seguro que es mejorable).

**Comment by willfrd** [comment]
Thanks for merging muy first airport @erikquinn :)

**Comment by erikquinn** [comment]
@willfrd Thank you for making it! It's very nicely done. :smiley:

**Comment by willfrd** [comment]
Thanks for that, expect future projects ;)

**Pull request merged**
