### PR TITLE
Missing aircraft, speech synthesis v0.0.1

### PR DESCRIPTION
**Pull request by daviessm**
The speech probably needs to be commented out by default until a UI is built to toggle it.

### CODE REVIEW

**Comment by Diastro** [comment]
We should add a toggle icon before pushing this.

**Comment by zlsa** [comment]
I'll hand-merge this later tonight and add an icon. Thanks, @daviessm!

**Comment by zlsa** [comment]
Sorry about the long delay - holidays got in the way. I'm working on this now.

**Comment by daviessm** [comment]
@zlsa no worries!

**Comment by zlsa** [comment]
Merged. Speech synthesis is disabled by default; click the speaker icon to toggle.

**Pull request closed without merging**
