### PR TITLE
New Airport: KLAS (McCarran International Airport)

### PR DESCRIPTION
**Pull request by Fechulo**
McCarran Intl. is the main airport in Las Vegas. There's various tall mountains to the west and the Grand Canyon to the east. There's some issues with the terrain, but it looks good enough to me.

With terrain:
with

Without terrain:
without

### CODE REVIEW

**Comment by Exfil** [comment]
Hi, I recently started playing the atc sim http://zlsa.github.io/atc/ . I love it so far but I would like to see SJU airport (https://skyvector.com/airport/SJU/Luis-Munoz-Marin-International-Airport) added. I found this page where one makes the requests for airports but I don't know how github works so I can't figure out how to write my own pull request since its asking me for stuff I'm not familiar with. I noticed you are active around here so I was hoping you could create the request for SJU airport to be added and oversee its creation.. I went to your profile but  I see theres no private message function, sorry to write it here :/ . I would be grateful if you could help me. Thanks!

**Comment by Fechulo** [comment]
I'm glad to hear you like the game! You could have also asked for it in the [issues section](https://github.com/zlsa/atc/issues) but here's fine too. I just took a quick look at the charts for San Juan and it looks like it's totally possible to add it to the game. I am currently working on another airport but as soon as I finish it I'll start on SJU.

**Comment by Exfil** [comment]
Thanks a lot man, take your time! Just let me know whenever you have a link or something where I can play it :)

**Comment by Fechulo** [comment]
No problem! I've never had a request before so I was surprised by your comment. I'll keep you updated.

**Comment by erikquinn** [comment]
Love it!!

**Comment by Fechulo** [comment]
Thank you! Currently working on KORD. Finding the Sector files for the TRACON ccordinates and video maps is resulting harder than I expected.

**Comment by erikquinn** [comment]
@Fechulo Oh me, oh my... lol that'll be a tough one! Will be good though, as that's the only thing anybody could ever argue that "the other" atc sim site has that we don't. :wink:

I can see if I can't get a hold of one of the ZAU guys and get the sector files for you, and hopefully some maps too, because I imagine the stratification won't be straightforward just from looking at the video map (though it won't be as nightmarish as new york or anything)... I'll let you know if I am able to get a hold of them.

**Comment by Fechulo** [comment]
I've already finished all SID's and STAR's, but I'm waiting on a sector file. It seems like the only way to get it is on the forums, but that's easier said than done. I created an account for the forums 4 days ago, but it needs to be approved by an admin, which may take a while. In the meantime I can start working on TJSJ!

**Pull request merged**
