### PR TITLE
added airport EBBR

### PR DESCRIPTION
**Pull request by stijnsanders**
see also:
- https://github.com/zlsa/atc/issues/3
- https://drive.google.com/file/d/0B78PfaNlYkBsVkJZUkdUdnhfOEk/view?usp=sharing

### CODE REVIEW

**Comment by zlsa** [comment]
Unfortunately, the scale looks very far off (EBBR's longest runway is 3km long; your airport has it as 20km long). Could you fix this?

(It's a big problem with other airports as well, and we're working on fixing them).

**Comment by Diastro** [comment]
I hate to be that guy but could you also fix the indentation before pushing?

**Comment by psycho202** [comment]
@zlsa Because the size of some airports at "true" scale is quite small, might it be a good choice to make the display scale together with the airport & its fixes?

**Comment by stijnsanders** [comment]
@zlsa: from where I stand, and I asked this before: what's the unit on `runways[].length`? if it's actually designed to be kilometer, I could set it at the values from the AIP and reverse engineer (again) from there. Funny thing is that would put most of the fixes listed on the EBBR AIP even further out... Unless I look at the VFR fixes again, though I assumed those aren't used with ILS (but I'm not a pilot, is that a wrong assumption?)

**Comment by Diastro** [comment]
The unit is for runway is km.

As for the fixes, in real life they are not all used for ils landing (you
can find which one are used if you look at a specific airport's approach
diagram).

Im working on a python tool that converts airport runways and fixes degrees
in km. You can use it to double check you distance if you wish.

**Comment by stijnsanders** [comment]
@zlsa about scale: get this: I took the [map here](http://www.belgocontrol.be/website/eaip/eAIP_Main/graphics/Ad/Ebbr/EBBR_ADC01_v28.pdf) looked at the ruler bottom right, and guessed how much meter was a second lat/long... But if you check 1000m on the ruler with the runway, you're already halfway! Guess the ruler's totally wrong...  Anyway, see my recent commit, I redid the scale, and though the fixes still made good sense, I dropped any that looked useless for this application.

**Comment by stijnsanders** [comment]
also, updated [this sheet](https://drive.google.com/file/d/0B78PfaNlYkBsVkJZUkdUdnhfOEk/view?usp=sharing)

**Comment by Diastro** [comment]
@stijnsanders Thank you for fixing the indentation.

The scale is looking good I think. With issue #69 I added a new parameter to the airport .json definition file (ctr-radius). You'll need to add this for your airport to work properly. See any up-to-date airport file for example. 

After this we'll be able to merge.

Quick note, make dure to get the latest code base (mainly ofr airport.js) ortherwise we can't merge automaticly (see the greyed out button below).

**Comment by zlsa** [comment]
I'm pretty sure @stijnsanders can't see the button as he's not a collaborator or owner.

Anyway it just says "We can't automatically merge this pull request. Use the command line to resolve conflicts before continuing."

**Comment by stijnsanders** [comment]
Yes I see the button, it says

```
This pull request contains merge conflicts that must be resolved.
Only those with write access to this repository can merge pull requests.
```

I've been reading up on how to fetch updates to a fork by doing a pull request, but am still confused since the new pull request button brings me back to here.

**Comment by Diastro** [comment]
Take a look at this : https://help.github.com/articles/syncing-a-fork/

**Comment by stijnsanders** [comment]
Thanks. I needed a pull request _from_ the upstream repo, had that the other way round. Strange it still envolves a local working dir though.

**Comment by Diastro** [comment]
Good job on the airport. 

If you have some time it would be even better if you could add some more waypoint  (since the CTR radius is 80km). I think having waypoint in a radius twice the radius of CTR is a good rule of thumb.

**Comment by stijnsanders** [comment]
That's the funny thing. I didn't find any when I went through the eAIP, I should have another look _or..._ ad the VFR fixes... still it seems unlogic to have _visual_ fixes when landing in _instruments_, but they're roughly within the ctr radius... I'll keep you posted. In the mean time I had a go at LFPO, but there also the fixes seem to make no sense whatsoever... https://github.com/stijnsanders/atc/commit/8434e6000cbd56e761663ff081687e557ccebc8a

**Comment by stijnsanders** [comment]
This is what I calculated from the VFR coordinates:

```
"AT":[15.06,-1.94],
"BE":[-4.25,3.24],
"CA":[-26.02,-3.24],
"GB":[27.36,-6.92],
"HO":[11.75,13.19],
"KH":[-8.93,-39.38],
"LO":[-4.23,22.91],
"ME":[2.4,-3.25],
"NO":[-3.4,8.2],
"PU":[22.3,0.62],
"SH":[-38.38,-4.49],
"TE":[12.44,-26.94],
"WA":[-2.57,-16.26],
"ZB":[-20.03,-43.19],
```

**Pull request merged**
