### PR TITLE
Separate control radius from radar range and add departure destinations

### PR DESCRIPTION
**Pull request by tedrek**
This is a pull request for feedback.  There are further changes required before merge.

Two major changes:
- Aircraft outside of airport.ctr_radius are not controllable - #134
- Aircraft have departure destinations - #29

I've tested this on KDBG only, all other airports will require some tuning before being playable.

The first change uses the center radius as the control zone, aircraft outside of the terminal area do not respond to commands and are displayed in a subdued manner.  Scoring for arrivals/departures occurs at the area boundary instead of the radar range.  To support this aircraft fly directly away from the airport upon leaving the area boundary.
One 'feature' which needs feedback here is the ability to order an aircraft to climb above the area ceiling to depart.  To use this clear an aircraft to 11,000 feet.

The second major change is adding aircraft departures, by default everything will depart due north.  The airport.json can specify different headings for departures.  A blue arc 10 degrees wide is shown at the area boundary to show where the aircraft must fly to score a valid departure.
Departure directions are included in this PR as a method for separating departures from arrivals outside of the terminal area.

A logical further development will be to eventually extend departure specification to be like arrivals.  This would allow some airlines do depart in certain directions more than others for example.

Before merge, all airports need to be updated with departure directions and arrivals to be certain they won't conflict with either departures or other arrivals prior to reaching the terminal area.

### CODE REVIEW

**Comment by glangford** [comment]
Some initial comments:

#### General
- shifts the balance of play between departures and arrivals
- allows greater focus on the control area
- future - do we want to add the ability to schedule heading or altitude changes to be followed only after a fix is reached?

#### Departures
- both more interesting from a game play standpoint and more realistic
- the blue destination arc is a good visual reminder - not visible when zoomed though
- should the arc be bigger?
- scoring could be less punitive; getting a departure safely off the ground but missing the arc is still a good thing
- no opinion on the 11,000 feet clearance at this point, but I am guessing that in some instances departing aircraft may be initially cleared to a low altitude under arriving aircraft, then later assigned a fix and higher altitude to leave

#### Arrivals
- more realistic to only be able to control aircraft within a defined radius
- less zooming in and out required to play since beyond range aircraft can't be controlled
- spawn locations, headings and spacing become more critical since player has no recourse to adjust them beyond range
- perhaps arriving aircraft could be assigned navigation fixes at spawn time

**Comment by tedrek** [comment]
A future ability to schedule commands after or at a fix would likely be desirable.  I think #147 could naturally create such a capability, it would also be the place to assign fixes at spawn time.

For departures I would like most airports to eventually have actual fixes instead of just a heading/radial.  This would make the arc visibility and size much less important.  The actual implementation would be nearly identical, but instead of a radial shown on the flight strip it would be a fix.  The fixes would be tuned to be very near the terminal boundary.

Scoring for failed departures should probably be reduced, it is equivalent to a failed arrival, which doesn't take into account missing by a small margin.

I will review and update all arrivals for all airports so there aren't any conflicts outside of the terminal area.  The assumption required of course will be that departures generally hit their destination radial.

**Comment by glangford** [comment]
> For departures I would like most airports to eventually have actual fixes instead of just a heading/radial. This would make the arc visibility and size much less important. The actual implementation would be nearly identical, but instead of a radial shown on the flight strip it would be a fix. The fixes would be tuned to be very near the terminal boundary.

Makes sense - I am just finishing an update to KMSP and I will add departure SID fixes to that update. (KJFK and KSFO should be updated with additional fixes also).

**Comment by tedrek** [comment]
All airports now have departure destinations, I didn't do any research I just paired a destination with each arrival.  Two new airlines were added, lightga and fastga.  Airports have been updated so arrivals are separated between jet aircraft and the slow prop aircraft of lightga.  Lightga arrivals should either be infrequent or have a speed set of 80-120 to keep aircraft from overtaking the previous one.  The only reason there should be conflicts outside the terminal area is if a departure is vectored outside of it's destination.

Departure failures score a -2 instead of a -20.

**Comment by nielsvdweide** [comment]
I still can't see these departure destinations. Did you implement this already?

**Comment by glangford** [comment]
It's in tedrek's development branch t-departure-destinations - it isn't merged yet.

**Comment by nielsvdweide** [comment]
I am terribly sorry, I still don't know how this thing works! Thanks for pointing this out to me!

**Comment by glangford** [comment]
> I am terribly sorry, I still don't know how this thing works! Thanks for pointing this out to me!

No problem, we are all learning from each other. :-)

**Comment by tedrek** [comment]
@zlsa, this is ready for merge from my perspective.

**Comment by zlsa** [comment]
I've been very much behind lately - thanks for pinging me @tedrek, I wouldn't have noticed otherwise.

**Comment by tedrek** [comment]
no worries @zlsa, thanks for making it in the first place and continuing to be the steward :smile:

**Pull request merged**
