### PR TITLE
[ready] Amsterdam Schiphol facelift

### PR DESCRIPTION
**Pull request by eliuuk**
Part of the project outlined in #650.

Checklist outlined by @Fechulo:
EHAM:
- [x] Update SIDs 
- [x] Update STARs
- [x] Terrain (Nothing interesting around EHAM that's worth seeing...)
- [x] Realistic airspace
- [x] Update departures list

http://www.ais-netherlands.nl/aim/2016-07-07-AIRAC/eAIP/html/index-en-GB.html

### CODE REVIEW

**Comment by Alpi-no** [comment]
Wow 80 sids.... damn

**Comment by Fechulo** [comment]
@jakobeng1303 It's actually 8 SID's but there's 6 runways and each one uses different waypoints so you end up with 80 different procedures.

**Comment by Alpi-no** [comment]
@Fechulo true :/

**Comment by Fechulo** [comment]
@indianbhaji Just out of curiosity, are you using some kind of program to add the SID's?

**Comment by eliuuk** [comment]
@Fechulo Nope, all hand done :p

**Comment by Fechulo** [comment]
Wow! :open_mouth:

**Pull request merged**
